.github/workflows/test.yml, src/lib.zig, src/time/time.zig, src/trace/entry.zig, src/trace/field.zig, src/trace/level.zig, src/trace/log.zig, src/trace/logfmt.zig
Added initial implementation for a basic logging/tracing module. Things that need to be introduced in future include: subscribers, multiple sinks, prometheus exporters, etc. For now, it's sufficient for logging to stderr.
=> Added initial trace/log implementation

src/bloom/bloom.zig, src/core/pubkey.zig, src/core/signature.zig, src/core/slot.zig, src/gossip/cmd.zig, src/gossip/gossip_service.zig, src/gossip/node.zig, src/rpc/client.zig, src/sync/channel.zig
misc changes for ping/pong verification:
- remove debug statements from tests 
- add verification of ping/pong msgs
=> update: ping/pong verification & update tests

src/common/lru.zig, src/lib.zig
Implemented an LRU cache that's bound my a max size including basic test
=> Implemented LRUCache with tests

src/sync/mux.zig
changed RwMux and Mux to move T to heap and added slice convenience method
=> changed RwMux and Mux

src/gossip/gossip_service.zig, src/gossip/ping_pong.zig, src/gossip/protocol.zig, src/sync/channel.zig, src/sync/mux.zig, src/trace/entry.zig
- `Channel` now uses `Mux` type
- `Mux` has new method `condition` which will call `wait` on condition with self
=> changed `Channel` to use new `Mux` type

src/cmd/cmd.zig, src/gossip/active_set.zig, src/gossip/crds_table.zig, src/gossip/gossip_service.zig, src/gossip/pull_response.zig
- changes variable function calls (and tests) to use `self: *Self` for improved readability
=> gossip: self function calls 

build.zig, src/bincode/bincode.zig, src/bloom/bloom.zig, src/cmd/helpers.zig, src/gossip/active_set.zig, src/gossip/crds.zig, src/gossip/crds_table.zig, src/gossip/fuzz.zig, src/gossip/gossip_service.zig, src/gossip/net.zig, src/gossip/node.zig, src/gossip/ping_pong.zig, src/gossip/protocol.zig, src/gossip/pull_request.zig, src/gossip/socket_utils.zig, src/sync/channel.zig, src/utils/arraylist.zig, src/utils/shortvec.zig
- build.zig : add gossip fuzz testing binary `gossip/fuzz.zig`
- bincode.zig : add custom free function for Config (used for Bloom + Shortvec + Arraylist) - (bug fix)
- crds.zig: add more random types 
- crds_table.zig: change HashTimeQueue from LinkedList to ArrayList (bug fix)
- gossip_service.zig: 
- `join_and_exit` to thread handles 
- free bincode allocations on errors (bug fix)
- socket_utils.zig: add docs + test to reproduce mac sending to ipv4 address leads to unexpected result + trace dump (linux just responds with `unreachable`)
- channel.zig: lock after checking close bool
=> gossip: add fuzz testing binary

src/common/lru.zig, src/gossip/active_set.zig, src/gossip/crds.zig, src/gossip/crds_table.zig, src/gossip/fuzz.zig, src/gossip/gossip_service.zig, src/gossip/net.zig, src/gossip/node.zig, src/gossip/ping_pong.zig, src/gossip/protocol.zig, src/gossip/pull_request.zig, src/gossip/socket_utils.zig
- `LruCache` has a cpl extra methods
- `PingCache` implementation
- Filter valid peers across `GossipService`
- Send periodic `Ping` packets as needed
=> Lru improvements & `PingCache` changes

src/cmd/cmd.zig
Fixes https://github.com/Syndica/sig/issues/66.
=> logging: fix metrics port not logged

src/core/accounts_db.zig
originally we were using map(pubkey, list(references)) but we are now using a linked-list approach for the keys bc its faster when indexing all the accounts
=> feat(accounts-db): faster account indexing

src/common/lru.zig
fixes #89 
adds two tests that failed until this change was implemented.
=> fix(lru): LruCache locks do not work

src/gossip/service.zig
```
time=2024-03-22T19:56:27Z level=info n_values=0 from_addr="BeSovDCzhEAfgwDyXBuhmCFKsu5WQ3PaX61GEfteNzXM" n_failed_inserts=0  gossip: recv push_message
time=2024-03-22T19:56:27Z level=info n_values=0 from_addr="BeSovDCzhEAfgwDyXBuhmCFKsu5WQ3PaX61GEfteNzXM" n_failed_inserts=0  gossip: recv push_message
/home/ubuntu/zig-linux-x86_64-0.11.0/lib/std/array_list.zig:243:40: 0x4c75fe in swapRemove (sig)
const old_item = self.items[i];
^
/home/ubuntu/sig/src/gossip/service.zig:1768:59: 0x48b00c in filterBasedOnShredVersion (sig)
_ = gossip_values_array.swapRemove(i);
^
/home/ubuntu/sig/src/gossip/service.zig:1446:65: 0x489c04 in handleBatchPushMessages (sig)
const valid_len = self.filterBasedOnShredVersion(
^
/home/ubuntu/sig/src/gossip/service.zig:605:45: 0x4a090e in processMessages (sig) …
```
=> fix(gossip): index out of bounds in filterBasedOnShredVersion

src/gossip/service.zig
sendSocket is failing because it's getting invalid packets over the channel. This is because PullRequestTask in gossip is deiniting the packet batch (which is an array list) even though it was sent over the channel and the ownership should have been transferred to the channel and ultimately to the other thread. The socket thread will deinit it when it's done with it.
This change makes it so the output is considered "consumed" after it is sent over the channel, and only outputs that have not been consumed will be deinited after processing the pull requests.
```
thread 5407 panic: index out of bounds: index 12297829382473034410, len 1232
/home/ubuntu/sig/src/net/socket_utils.zig:133:64: 0x4accd2 in sendSocket (sig)
const bytes_sent = socket.sendTo(p.addr, p.data[0..p.size]) catch |e| {
^ …
```
=> fix(gossip): index out of bounds on pull response packet batch

src/net/net.zig
Added formatting to `SocketAddr` and other types so we can view addresses properly
=> feat(net): add formatting to `SocketAddr` and other types

LICENSE
This PR simply switches our AGPL license to Apache 2.0
=> Changing license to Apache 2.0

src/gossip/data.zig
=> fix(gossip): impl sanitize for Version

src/gossip/service.zig
log a summary of received messages every 10 seconds instead of logging every time the loop iterates
=> feat(gossip): cleaner gossip summary log

build.zig, build.zig.zon, src/accountsdb/db.zig, src/core/account.zig, src/core/hash.zig, src/core/shred.zig, src/gossip/data.zig, src/gossip/pull_request.zig, src/gossip/shards.zig, src/gossip/table.zig
Hi, I'm beginning to familiarize myself with the codebase by diving in and applying improvements to organization & bug fixes. I started by hoisting the "Hash" type into a file struct, allowing more convenient import (`@import("Hash.zig")` instead of `@import("hash.zig").Hash`).
I also took the liberty of moving the inline namespace in `lib` to a `core/core.zig` "index" file, which puts the set of "exports" closer to the actual module, making it less likely for it to ever go out of sync with the existing modules.
It should be noted that the continued use of usingnamespace is potentially dubious, as there is more than a decent amount of energy in the zig project to possibly remove it; there is no official issue to do so at the time of writing this, however discussions alluding to such have …
=> build script refactor, suggested improvements, and fixes

.github/workflows/abi_watch.yml
adds the .yaml config for running the abi script
=> feat(ci): cron job to watch for ABI changes

build.zig
* Removes superfluous manual linking of curl & zstd libraries, which are already linked by their respective build functions.
* Add `filters` instead of supplying one test filter via `b.args[0]`.
* Use `b.path` instead of the now deprecated `path` field in `LazyPath`.
* Unroll the loop declaring the `fuzz` and `benchmark` steps. This also resolves the TODO regarding not needing all dependencies for all of the executables.
* Group top level step declarations together at the beginning of the build function.
* Don't add `zig-cli` import to the sig executable twice.
* Install all compile step artifacts for convenient debugging.
* Use more consistent naming for dependency declarations.
* Use `addImport` instead of declaring the dependencies for the sig module up front; it's a lot more concise, …
=> refactor(build.zig): updates for latest zig & improvements

src/accountsdb/accounts_file.zig, src/core/pubkey.zig
by making them `extern struct`s.
=> fix(core,accountsdb): Guarantee the layout of some struct types

src/cmd/cmd.zig, src/gossip/service.zig, src/shred_collector/service.zig, src/shred_collector/shred_processor.zig, src/shred_collector/shred_verifier.zig
some threads in the repair service werent properly exiting because they were missing the exit atomic - this pr fixes it so they all exit as expected on deinit
=> fix(repair): add exit signals to threads

src/gossip/service.zig, src/gossip/table.zig
**GossipTable.remove**
The call to free the gossip data associated with the removed label actually freed the gossip data associated with the label swapped into its place in the store. This happened because the data pointed to by versioned_value is swapped with the last entry of the store or set to undefined when we call store.swapRemove, the subsequent call to bincode.free(..., versioned_value.value.data) then frees the incorrect gossip data.
Moving the call to bincode.free(..., versioned_value.value.data) above the call to store.swapRemove fixes the issue.
Note: *When updating the index tracking of the 'swapped' value, we can now use versioned_value instead of retrieving the value from the store again as it will necessarily point to the value we need to update tracking for. Perhaps …
=> fix(gossip) fix GossiptTable.remove freeing wrong gossip data, fix memory leak in GossipService.processMessages

src/sync/mux.zig
Extracted from: https://github.com/Syndica/sig/pull/202#issuecomment-2251162036
This (luckily unused) `toConst` function returns a pointer to a local when the parameter isn't a pointer, which could/would use to a UAF if used.
=> fix(synx): Remove dangerous & unused `toConst` & refactor `Const`

src/fuzz.zig
Two improvements:
- Moved error handling/reporting to same place
- Include the supported fuzz filters in error message.
=> feat(cli): improvement to fuzz cli filter 

src/accountsdb/db.zig
The defer for the list clearings was being done in the if block, leading to the lists becoming cleared before the lists are actually passed as function arguments, meaning no slots were being cleaned, flushed, shrunk, or deleted.
=> fix(accountsdb): move defer outside of if block, improve logs

readme.md
Signed https://github.com/Syndica/sig/pull/244 so I can merge it. I'm sure there's a better workflow for this...
=>  (singed copy) chore: actualize main readme.md #244 

misc/prometheus_grafana/grafana/dashboards/accountsdb_metrics.json, src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/cmd/cmd.zig, src/fuzz.zig, src/prometheus/http.zig, src/prometheus/lib.zig
https://github.com/orgs/Syndica/projects/2?pane=issue&itemId=68540818
Dashboard preview:
=> feat(accountsdb): improved metrics

src/rpc/client.zig, src/rpc/types.zig, src/transaction_sender/service.zig
Motivation:
provide the ability to use custom URLs for sending txs
=> feat(rpc): add custom cluster url

src/accountsdb/snapshots.zig, src/cmd/cmd.zig, src/core/leader_schedule.zig, src/transaction_sender/leader_info.zig
The basic idea is that the core/leader_schedule.zig previously contained some glue code that was responsible for connecting possible sources for a leader schedule with the construction and caching of the leader schedule. I moved the glue code into the places where it is actually used.
The motivation here is to make the code easier to understand, and to reduce lock-in for a particular way of doing things.
easier to understand:
- simplify structs towards more focused and clearer responsibilities (e.g. LeaderScheduleCache)
- unify code for a particular use case into a single place (e.g. glue code in the LeaderInfo)
- simplify dependency graph
reduce lock-in:
- remove abstractions that are only used in one place, and are more complex than what is currently needed
- reduce coupling between …
=> refactor(leader-schedule): simplify core leader schedule code

src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/accountsdb/snapshots.zig, src/cmd/cmd.zig, src/utils/tar.zig
Closes #282.
There is likely room for more optimizations, but this sets a good foundation for that work, and I think keeping this down in scope and easy-ish at this level of review would be best - more work can be done in a follow up PR.
=> perf(accountsdb): begin optimizing snapshot generation

src/accountsdb/db.zig
=> enhancement(accountsdb): Cache validated snapshot hash & capitalization

scripts/agave_gossip_hash_check.py
for some reason the ci script fixes were not included in https://github.com/Syndica/sig/pull/343 (?) -- this just fixes the ci script so the action passes correctly
=> fix(ci): update stable commit for action

src/accountsdb/download.zig
=> Fix out-of-bounds access during url sentinel-slice

src/ledger/cleanup_service.zig, src/ledger/reader.zig, src/ledger/result_writer.zig, src/ledger/schema.zig, src/ledger/shred_inserter/shred_inserter.zig, src/ledger/shred_inserter/slot_chaining.zig
- roots -> rooted_slots
- orphans -> orphaned slots
=> refactor(ledger): rename column families roots and orphans

src/shred_collector/shred_verifier.zig
This improves the performance of signature verification in the shred collector by a factor of up to 64.
The shred signature signs the merkle root. Since all the shreds from an erasure set share the same merkle root, you actually only need to verify the signature once for that merkle root, then every shred from the erasure set should be considered "verified" as long as you can reproduce the merkle root from its merkle proof.
Before this pr, the code was redundantly verifying the signature of the merkle root for every single shred. This leads to a performance bottleneck in the shred verifier because signature verification is computationally expensive.
This change removes the redundancy. It uses an lru cache to keep track of the last 1024 merkle roots to be verified.
=> perf(shred-collector): cache verified merkle roots

src/bincode/bincode.zig
- see doc comment on how this new field is useful
- we also remove dead test code
=> feat(bincode): config default values

metrics/compose_linux.yaml, metrics/compose_mac.yaml, metrics/grafana/dashboards/node_exporter.json, metrics/grafana/datasources/datasource.yml, metrics/prometheus/prometheus.yml
adds support for node-exporter which more details can be found here: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
=> feat(dashboards): add cpu/mem metrics

src/accountsdb/db.zig, src/accountsdb/index.zig, src/utils/allocators.zig
- integrates new reference allocator into adb
=> feat(accountsdb): integrate improved reference allocator

src/cmd/cmd.zig
- removes old and unused `initGossip` method
=> fix(cmd): fix downloadSnapshot gossip loading

src/utils/allocators.zig
=> fix(db/fuzz): ref allocations #2

src/gossip/service.zig
This comment was accidentally resolved on a prior PR without being addressed: https://github.com/Syndica/sig/pull/413#discussion_r1876526853
This PR is what I had in mind with my suggestion.
=> refactor(gossip): improve PullRequestTask.deinit

src/gossip/message.zig, src/gossip/service.zig
another mem leak bites the dust - no more leaks occur on the gossip fuzzer
=> fix(gossip): prune mem leak

src/rpc/client.zig
these tests are blocking all of our other prs. a follow-up pr can actually convert these tests into something that works locally without internet access
=> fix(rpc): skip rpc client tests

src/accountsdb/bank.zig, src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/accountsdb/snapshots.zig, src/cmd/cmd.zig, src/rpc/server.zig
Deduplicate the `base_slot` in `SnapshotFiles`.
Simplify the full field, and remove some functions
=> refactor(snapshots): Deduplicate the `base_slot` in `SnapshotFiles`.

build.zig
Reuse the `defaultTargetDetectM3()` workaround for m4 cpus as well.
=> fix(build): support m4 cpus

src/accountsdb/bank.zig, src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/accountsdb/fuzz_snapshot.zig, src/accountsdb/lib.zig, src/accountsdb/snapshots.zig, src/cmd/cmd.zig, src/rpc/server.zig
Rename, refactor, and re-organize some stuff
Refactor & re-organize more snapshot type stuff
Remove unused `StakeStateV2`
=> refactor(snapshots): Rename, refactor, and re-organize some stuff

src/accountsdb/snapshots.zig
and refactor some things along the ways
=> refactor(snapshots): Add clone method to snapshot types and refactor some things along the ways

src/accountsdb/buffer_pool.zig
.read currently fails tests on macos because of this bug.
=> fix(bufferpool, accountsdb) fix up readBlocking

src/prometheus/registry.zig
Spotted by tsan. e.g. https://github.com/Syndica/sig/actions/runs/13139962124/job/36664738694
There's a few more for sure, related to our alloctor usage. Going to follow this up another.
=> fix(prometheus) fixed threadsafety bugs in prom registry

readme.md
- Cleaned up some of the docs
- Fixed some incorrect information
=> fix(docs): update the `README.md`

src/rpc/server/basic.zig, src/rpc/server/linux_io_uring.zig, src/rpc/server/requests.zig
* Fixes a lock guard leak in certain codepaths.
* Refactors the linux io_uring backend `Entry` definition to properly allow for more than just the `ACCEPT` alt allocationless state.
* Flushes headers in the basic server preemptively.
* Factor out http version into a constant in linux io_uring backend.
* Handle `/health` route, returning skeleton "unknown".
* Add skeleton tag for handling genesis file requests.
=> refactor(rpc server): RPC Server refinements

src/gossip/service.zig
Previously scheduled and waited for one-by-one. Now scheduled together and wait using a `Thread.WaitGroup`.
=> nit(gossip): schedule PullRequestTasks in bulk

src/accountsdb/snapshots.zig
First step to beginning to fix #536
=> fix(snapshots): Unconditionally write rooted slots & hashes

src/svm/main.zig, src/svm/syscalls.zig, src/svm/tests.zig, src/svm/vm.zig
=> feat(svm): integrate logger into syscalls

src/svm/elf.zig, src/svm/executable.zig, src/svm/main.zig, src/svm/tests.zig
After a grueling day in the fuzzing mines, I've returned with fixes o' plenty.
=> fix(svm): more conformance!

src/utils/io.zig
This commit adds some unit-tests for the PeekableReader in utils/io.zig.
=> Add tests for PeekablebReader

build.zig
Two bugs are fixed here:
`send-file.zig` requires libc due to using c_allocator.
Using options `ssh-host` and `no-run` means the binary should be sent to the remote server but not run. It was only building locally and not sending it. It would only send it when it's supposed to run (i.e. no-run was not specified). This is because the build step dependencies were incorrectly specified.
=> fix(build.zig): ssh step dependencies

src/runtime/executor.zig, src/runtime/program/lib.zig, src/runtime/program/system_program/execute.zig, src/runtime/program/system_program/lib.zig, src/runtime/program/vote/execute.zig, src/runtime/program/vote/lib.zig
Improves error semantics for instruction invocation
=> refactor(runtime): improve error return

build.zig.zon, src/vm/executable.zig, src/vm/syscalls.zig, src/vm/tests.zig
Quick fixup so that the example in the blogpost can run
Also moved our deps to using the git over HTTP protocol since it's a bit smarter and there's no reason we can't take advantage of it.
=> fix(svm): resolve some TODOs in the asm parser

build.zig
When working on the ELF tests, we rely on outside binaries which aren't in the cache. This means that changing them won't invalidate the test. I think it makes sense to mark the test run step as impure, so this PR adds an option to do that.
=> fix(build): add an option to make the test run not cache

src/cli.zig, src/cmd.zig, src/geyser/main.zig, src/vm/main.zig
todo: generate help output for positional arguments
=> feat(cli): add ability to specify positional arguments

src/consensus/fork_choice.zig, src/runtime/borrowed_account.zig, src/runtime/program/lib.zig, src/runtime/program/serialization.zig, src/runtime/program/vote/state.zig, src/runtime/testing.zig, src/vm/memory.zig
Implements basic serialisation and deserialisation of parameters for BPF execution. 
Some testing is implemented, more testing will be added in follow up BPF execution PR.
=> feat(runtime): Implement parameter serialisation

src/vm/executable.zig, src/vm/main.zig, src/vm/memory.zig, src/vm/sbpf.zig, src/vm/syscalls.zig, src/vm/tests.zig
- Implemented unaligned memory maps
- Reworked the memory map code to make errors match agave
- Testing
=> feat(vm): unaligned memory map

src/bincode/int.zig, src/runtime/executor.zig, src/runtime/features.zig, src/runtime/instruction_info.zig, src/runtime/program/bpf/execute.zig, src/runtime/program/bpf/lib.zig, src/runtime/program/bpf_loader/execute.zig, src/runtime/sysvar/epoch_schedule.zig, src/runtime/testing.zig, src/vm/elf.zig, src/vm/syscalls.zig
Bug fixes for bpf-loader-conformance. Passing all public test-vectors for instructions excluding the v4 loader
=> feat(runtime): bpf-loader conformance (instructions only)

src/cli.zig, src/cmd.zig, src/geyser/main.zig
To discuss: are the new doc comments by themselves in this format sufficient, or would they be improved as a separate markdown document?
Don't pay too much attention to the code changes, they are minor implementation-facing improvements and small API-relevant details I noticed while writing the documentation.
=> feat(cli,cmd,geyser): Document the library - refactor & fix some minor details

build.zig.zon, src/core/instruction.zig, src/runtime/borrowed_account.zig, src/runtime/compute_budget.zig, src/runtime/executor.zig, src/runtime/program/address_lookup_table/execute.zig, src/runtime/program/bpf_loader/execute.zig, src/runtime/program/vote/state.zig, src/runtime/stable_log.zig, src/runtime/sysvar/lib.zig, src/runtime/transaction_context.zig, src/vm/executable.zig, src/vm/interpreter.zig, src/vm/lib.zig, src/vm/memory.zig, src/vm/syscalls/cpi.zig, src/vm/syscalls/lib.zig, src/vm/syscalls/memops.zig, src/vm/tests.zig
**ExecutionError**
The main change in this PR is the definition of the ExecutionError which is an error set consisting of the union of InstructionError, EbpfError, SyscallError, and some Sig specific errors. InstructionError.ArithmeticOverflow has been renamed to InstructionError.ProgramArithmeticOverflow to avoid conflicting with SyscallError.ArithmeticOverflow. It is necessary to understand which error set an error belongs to for conformance and logging.
=> feat(vm): syscall conformance

src/runtime/transaction_context.zig, src/vm/syscalls/lib.zig, src/vm/syscalls/memops.zig
Getting the memory syscalls to pass conformance fuzz testing
=> fix(runtime): mem_ops conformance

scripts/style.py, src/runtime/compute_budget.zig, src/vm/interpreter.zig, src/vm/main.zig, src/vm/syscalls/ecc.zig, src/vm/syscalls/hash.zig, src/vm/syscalls/lib.zig, src/vm/syscalls/memops.zig, src/vm/tests.zig
=> feat(svm): more cryptographic syscalls

src/consensus/lib.zig, src/consensus/progress_map.zig, src/core/bank.zig, src/core/stake.zig, src/sig.zig, src/testing.zig
First pass which mirrors the rust implementation and has a unit test
validating that the ownership semantics in and between all of the
data structures are sound.
Provides minimal implementations of two functions that may be needed
imminently.
=> feat(consensus): Implement `ProgressMap`

src/runtime/compute_budget.zig, src/runtime/pubkey_utils.zig, src/vm/memory.zig, src/vm/syscalls/cpi.zig, src/vm/syscalls/hash.zig, src/vm/syscalls/lib.zig
Implement `sol_try_find_program_address` and `sol_create_program_address`. Both passing conformance tests.
=> feat(runtime): program address syscalls

src/vm/syscalls/ecc.zig, src/vm/syscalls/hash.zig
I can feel it, we're getting close!
=> fix(svm): some more syscall fixes

src/consensus/lib.zig, src/consensus/vote_tracker.zig, src/sync/reference_counter.zig
ReferenceCounter: don't use `Self`
VoteTracker MVP
=> feat(consensus): Implement VoteTracker

build.zig.zon, src/runtime/executor.zig, src/runtime/features.zig, src/runtime/instruction_context.zig, src/runtime/program/bpf/execute.zig, src/runtime/program/bpf/serialize.zig, src/runtime/transaction_context.zig
=> fix(svm): improve agave v2.2.13 conformance

src/bincode/bincode.zig, src/runtime/program/system/instruction.zig, src/runtime/program/vote/instruction.zig
Simpler usage, facilitates bounded array
=> refactor(bincode,runtime): replace `readUtf8String` with `utf8StringCodec`

src/consensus/vote_listener.zig
Expands the inputs, and makes the logic more easily parameterizable.
Also adds comments referencing the relevant logic.
Also attempts to Makes it less flakey, though this seems unsuccessful. This will be properly addressed in a follow up change.
=> refactor(consensus:vote_listener): refactor the vote listener unit test to better "parameterize" it

conformance/build.zig
* Add no-bin & no-run options.
* Define all options and steps at the top.
* Refine the protobuf step description.
* Normalize suffixes and naming conventions.
=> refactor(conformance): refactor build.zig

conformance/scripts/fixtures.sh
https://github.com/firedancer-io/solana-conformance/pull/139 got merged, we need to update the CLI commands
=> fix(ci): add `-o` option to solana-conformance

conformance/scripts/passing_txn_fixtures.txt, conformance/src/bank_methods.zig, conformance/src/verify_transaction.zig, src/consensus/vote_listener.zig, src/core/account.zig, src/core/bank.zig, src/core/lib.zig, src/core/reserved_accounts.zig, src/core/transaction.zig, src/replay/confirm_slot.zig, src/replay/edge_cases.zig, src/replay/execution.zig, src/replay/resolve_lookup.zig, src/replay/scheduler.zig, src/replay/service.zig, src/replay/trackers.zig, src/runtime/account_loader.zig, src/runtime/executor.zig, src/runtime/ids.zig, src/runtime/sysvar/instruction.zig
Passed: 3377, Failed: 538 (~86.2%)
=> feat(runtime): implement reserved account keys with feature activations

conformance/scripts/passing_txn_fixtures.txt, src/core/instruction.zig, src/runtime/program/precompiles/ed25519.zig, src/runtime/program/precompiles/secp256k1.zig
=> fix(precompile): set custom error to zero on precompile verify failure

conformance/scripts/passing_txn_fixtures.txt, src/runtime/program/zk_elgamal/execute.zig
=> fix(programs): fix account borrow in zk elgamal

conformance/scripts/passing_txn_fixtures.txt, src/runtime/transaction_execution.zig
=> fix(runtime): check transaction account limit (tx-lock-limit)

conformance/scripts/passing_txn_fixtures.txt, src/runtime/program/vote/state.zig
=> fix(vote-program): fix compact vote state serialisation

build.zig, src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/accountsdb/manager.zig
Slew of improvements to the accountsdb fuzzer
=> refactor(accountsdb:fuzz): General improvements to the fuzzer

src/accountsdb/account_store.zig, src/accountsdb/db.zig, src/accountsdb/fuzz.zig, src/accountsdb/manager.zig, src/accountsdb/snapshot/load.zig, src/replay/service.zig
Will follow up with another PR for snapshot generation
=> fix(replay): get the accountsdb manager working
