Syndica/sig

src/common/lru.zig

- Added methods `contains`, `remove`, `mru` and `lru`
- Added `len` field 
- Use of `std.mem.swap` instead of `allocator.destroy` when reach `max_items` to save `free` and `alloc` syscalls
- Added basic comments/doc

Improvements to LruCache

---

build.zig
src/gossip/gossip_service.zig
src/trace/entry.zig
src/trace/log.zig

- Fixed channel types to observe Channel.init returns `*Channel` instead of `Channel` now
- Removed comment from `build.installArtifcact(exe)`
- Made logger `spawn` func public

Test fixes for latest push

---

src/sync/mux.zig

Implemented a `Mutex` wrapper that enforces access to protected data by acquiring a `LockGuard`. This is simply to enforce proper access of protected data by joining both the `Mutex` with the data it protects.

implemented simple Mutex wrapper for safe access to protected vals

---

src/sync/mux.zig

- Removed need for allocations
- Made API more protective over data
- Introduced `Const(T)` and `Mutable(T)` types which convey intents and enforce proper access
- Changed `valid` checks in guards to only update/checked if in `.Debug` mode

Removed alloc requirement & improved safety to `Mux` and `RwMux`

---

src/bincode/bincode.zig
src/gossip/crds.zig
src/gossip/crds_shards.zig
src/gossip/crds_table.zig
src/gossip/gossip_service.zig
src/gossip/net.zig
src/gossip/readme.md

- bounds memory growth for gossip data

gossip: triming crds table values

---

src/gossip/cmd.zig
src/main.zig

Windows compilation

---

build.zig
src/cmd/snapshot_utils.zig
src/cmd/snapshot_verify.zig
src/common/merkle_tree.zig
src/core/account.zig
src/core/accounts_db.zig
src/core/append_vec.zig
src/core/snapshot_fields.zig
src/lib.zig
src/sync/thread_pool.zig

`build.zig`
- make it easy to add new executables with all the required modules
`src/cmd/snapshot_utils.zig` 
- snapshot utils for: 
- dumping the `accounts_db.bincode` from the full bank metadata (the full bank metadata is quite large, and we only need the accounts_db fields  to correctly parse the append_vecs) 
- dump accounts found in append vec into a .csv format (TODO: current approach contains duplicate accounts + not most recent -- will likely need to merge logic with account hash verification which does this sorting) 
`src/cmd/snapshot_verify.zig` 
- logic for verifying the account hash of a snapshot matches the metadata 
- TODO: is currently slow relative to rust-impl -- should be able to optimize it
`src/common/merkle_tree.zig`
- simple merkle tree hash calculation …

accounts-db: snapshot utils + hash verification

---

src/bincode/bincode.zig
src/common/lru.zig
src/gossip/crds.zig
src/gossip/gossip_service.zig

Fixes #45 and other bugs found in `19/gossip_optim_v2` branch when connecting to mainnet with `spy_node = false` at `cmd.zig:118`
```bash
sig gossip --entrypoint 34.83.231.102:8001 --entrypoint 145.40.67.83:8001 --entrypoint 147.75.38.117:8001 --entrypoint 145.40.93.177:8001 --entrypoint 86.109.15.59:8001
```
```
thread 2042986 panic: index out of bounds: index 64, len 64
/Users/drew/mine/code/sig/src/gossip/gossip_service.zig:383:37: 0x102b6c107 in verifyPackets (sig)
var task = tasks[count];
^
/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/Thread.zig:433:13: 0x102b5b04f in callFn__anon_21748 (sig)
@call(.auto, f, args) catch |err| {
^
/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/Thread.zig:685:30: 0x102b41863 in entryFn (sig)
return callFn(f, args_ptr.*);
^
```
<details><summary>full …

gossip: bug fixes

---

src/gossip/active_set.zig
src/gossip/gossip_service.zig

Fixes #50
Multiple contacts with the same pubkey were being passed to the rotate method. This resulted in duplicate items being included in the array, but the hashmap internally prevents duplicates. So the next time rotate is called, it would iterate through the array and attempt to deinit the same hashmap entry twice.
Remove the peers and len fields from ActiveSet and just use the hashmap. It has the same data already and it's already internally consistent and avoids bugs like this where we don't keep the data consistent with two unnecessary fields.
This was the original solution before switching to above based on feedback:
Duplicates could be detected and skipped during the insertion loop by checking for their presence in the hashmap.

fix(gossip): Double free in ActiveSet

---

src/cmd/cmd.zig
src/gossip/gossip_service.zig
src/gossip/socket_utils.zig
src/lib.zig
src/trace/entry.zig
src/trace/log.zig
src/utils/types.zig

- Add cli option to enable spy node so the bool doesn't need to be edited in the code
- Add cli option for log level to customize the granularity of log messages to log
- Change some log messages that indicate errors to log at the error instead of debug level
- Remove redundant newlines from some log messages in gossip
I made it default to *not* run as a spy node. You'll need to specify the flag to run as a spy node. This is contrary to the current behavior, which runs as a spy node (unless you edit the source code). I did this because it lent itself to the most intuitive command-line interface. It seemed a little confusing to have a CLI flag that only served to *disable* spy_node mode. It's not clear to me what name to give to a normal gossip node that isn't spying.
It's also not …

cli options for spy node and log level

---

src/gossip/gossip_service.zig
src/gossip/node.zig
src/gossip/protocol.zig

fixes #61
https://github.com/solana-labs/solana/pull/32309 added a new field to ContactInfo called `extensions`. The field must be supported for serialization because it adds an extra byte to the serialization format to represent the length of the vec. The type contained in the vec is 0-sized, so that's the only data it adds.
When a pull response is received from another node, the message is deserialized to extract the signature and the pubkey, and then it is re-serialized to validate the signature+pubkey against the serialized version of the message. 
Since we're missing the `extensions` field, when re-serializing the ContactInfo, it is missing that last byte. Since the signature was created for a ContactInfo including that byte, our signature verification process fails. This was causing …

fix(gossip): Add `extensions` field to ContactInfo

---

src/cmd/cmd.zig
src/prometheus/registry.zig

This adds a function for the prometheus registry so you can access the global registry anywhere with a simpler function call.
This change has three goals:
- Make it clearer how to access the registry rather than needing to worry about how to correctly use a OnceCell. 
- Guarantee there cannot be errors/panics/ub when accessing the global registry.
- Enable us to change the approach to global variables if ever desired, without breaking compatibility.

feat(prometheus): global registry init/get: make infallible and more ergonomic

---

src/cmd/cmd.zig
src/gossip/active_set.zig
src/gossip/crds.zig
src/gossip/crds_shards.zig
src/gossip/crds_table.zig
src/gossip/fuzz.zig
src/gossip/gossip_service.zig
src/gossip/node.zig
src/gossip/ping_pong.zig

fixes #65 
Previously, ContactInfo only had the bare minimum support. It could be deserialized from incoming messages, stored in the CrdsTable, and sent out to other nodes. Sig did not represent its own contact info with ContactInfo. It only used LegacyContactInfo for this purpose. Also, when identifying other gossip nodes, Sig only ever looked for LegacyContactInfo.
With this change, Sig stores its own contact info internally as a ContactInfo, and publishes it as both LegacyContactInfo and ContactInfo. When identifying other gossip nodes from the CrdsTable, it looks for both ContactInfo and LegacyContactInfo. The logic that interprets these contact infos now solely uses ContactInfo instead of LegacyContactInfo, which means all LegacyContactInfo instances are converted to ContactInfo for …

feat(gossip): upgrade fully to ContactInfo

---

src/gossip/table.zig

fixes #96
#87 also fixes the same bug. if that one is merged first, this pr can be closed.
This fixes the issue where gossip panics during buildPullRequests because it got an invalid ContactInfo with a SocketAddr containing an invalid tag. The cause is that the buf returned from getContactInfos is not filled contiguously. some buf indices are skipped because the item is too old, and it is excluded by an if statement.
The fix is to track the source and target indices separately. only push the target index if an item was actually inserted.

fix(gossip): panic: switch on corrupt value - SocketAddr from ContactInfo during buildPullRequests

---

src/core/transaction.zig
src/gossip/data.zig

fixes #90 
These messages did not have `sanitize` implemented and it results in some occasional errors in gossip.

fix(gossip): Implement sanitize for ContactInfo, Message, NodeInstance, and SnapshotHashes

---

src/cmd/cmd.zig
src/gossip/service.zig
src/net/net.zig

fixes #88 
Currently gossip is publishing 0.0.0.0 as its IP address, which is a bug.
With this change, sig determines its IP address using the [same logic as agave](https://github.com/anza-xyz/agave/blob/d88050cda335f87e872eddbdf8506bc063f039d3/validator/src/main.rs#L1755-L1792). The value is selected from one of these three approaches, in this order of precedence:
1. CLI option `--gossip-host` (if specified)
2. Received from an entrypoint via IP echo. try each entrypoint until we get a response
3. 127.0.0.1 (hardcoded fallback)

fix(gossip): publishes wrong IP address

---

prometheus-grafana/README.md
prometheus-grafana/compose.yaml
prometheus-grafana/grafana/dashboards/dashboards.yaml
prometheus-grafana/grafana/dashboards/sig_dashboard.json
prometheus-grafana/grafana/datasources/datasource.yml
prometheus-grafana/prometheus/prometheus.yml
prometheus-grafana/run.sh
src/gossip/service.zig
src/gossip/table.zig
src/prometheus/counter.zig

added metrics across the gossip service (src/gossip/service.zig) along with a docker compose setup to build a local prometheus and grafana server with the gossip dashboards
metrics are similar to the core rust client implementation - we also take the same approach of saving the metrics in a struct and then publishing all those metrics every 2 seconds (in the buildMessages loop)

feat(gossip): add prometheus metrics

---

.gitignore
build.zig
build.zig.zon
readme.md
src/cmd/cmd.zig
src/main.zig
src/net/echo.zig
src/net/net.zig

Previously, we needed to resolve entrypoint DNS manually and pass IPs to the startup command like so: 
```sh
sig gossip --entrypoint 34.83.231.102:8001 \
--entrypoint 145.40.67.83:8001 \
--entrypoint 147.75.38.117:8001 \
--entrypoint 145.40.93.177:8001 \
--entrypoint 86.109.15.59:8001
```
Now, we can pass the domains directly and Sig will resolve DNS:
```sh
sig gossip --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint5.mainnet-beta.solana.com:8001
```
This PR adds new dependency on [`zigdig`](https://github.com/lun-4/zigdig/) which is only used to resolve DNS. I've reviewed the code and its safe.

feat(gossip): resolve entrypoint(s) dns records

---

src/gossip/service.zig
src/gossip/table.zig

The processMessages loop typically runs pretty fast, many times per second, until a certain point when it gets bottlenecked by an overwhelming number of push messages and is unable to catch up. The iteration duration grows exponentially until it takes minutes to deal with tens of thousands of messages. This continues for several minutes, until sig reaches a degenerate state where it is no longer receiving messages. The pull request thread is unable to identify any peers. This continues indefinitely. I have observed it continue for hours.
@0xNineteen confirmed that push messages are taking significantly longer to process than other messages:
I timed individual pieces of handleBatchPushMessages and found that just the log messages alone accounted for around 70% of the execution time. Next …

perf(gossip): speed up handleBatchPullMessages

---

prometheus-grafana/compose.yaml
prometheus-grafana/grafana/dashboards/sig_dashboard.json
prometheus-grafana/prometheus/prometheus.yml
src/gossip/service.zig

prev implementation was a large bottleneck which would spawn a thread per packet and wait sequentially before scheduling a new thread for the next packet (a lot of thread overhead) and waited for all threads to be completed before draining new packets
this fix 
- assigns packet batches to each thread (arraylist(packet) vs packet) 
- schedules them on any free task
- and doesnt wait for all the tasks to complete before draining from the channel

perf(gossip): improve packet verification

---

src/gossip/service.zig

Previously, we used PACKETS_BER_BATCH threads to process messages, because one thread was dispatched for each individual packet. This was intended to process a full packet batch at one time, but it was very inefficient, likely due to context switching and cache misses, which caused significant bottlenecks.
#110 addressed this by changing the logic to process entire packet batches within a thread, instead of just single packets. Now, there is no particular reason for the number of threads to equal PACKETS_PER_BATCH.
But we're still using PACKETS_PER_BATCH for the number of threads. That's 64 threads. This *might* have been useful on machines with high core-counts when the large number of threads was necessary to process a single batch at once. But now that a single thread can more …

perf(gossip): Use 4 threads to verify messages

---

prometheus-grafana/README.md
prometheus-grafana/compose-linux.yaml
prometheus-grafana/compose-mac.yaml
prometheus-grafana/compose.yaml
prometheus-grafana/grafana/dashboards/sig_dashboard.json
prometheus-grafana/prometheus/prometheus.yml
prometheus-grafana/run.sh
src/accountsdb/db.zig

this updates the `.json` dashboard for sig to have new naming
this also updates the config files + readme to support running on both linux and mac (prev was broken on mac)
note: forgot to include updated .json in #117 since UI updates are pushed to the running docker container (not the local machine)

fix(prometheus): update config + dashboards

---

src/accountsdb/db.zig
src/cmd/cmd.zig
src/common/merkle_tree.zig
src/gossip/fuzz.zig
src/gossip/service.zig
src/main.zig
src/utils/thread.zig

* Switch from `std.ArrayList` to `std.ArrayListUnmanaged` to save memory in some cases.
* Improve `spawnThreadTasks` to output into a caller-provided arraylist, allowing them the ability to properly clean up even in the error path. Also document more precisely.
* Use tuple destructuring feature now available in zig 0.12.
* Constify certain things not caught by zig's ast checks.
* Fix leaks.
Supercedes #142.

fix(gossip,accountsdb): removed leaks in error path, constified things, pass slices instead of ArrayList

---

build.zig.zon
src/accountsdb/snapshots.zig
src/cmd/cmd.zig
src/gossip/fuzz.zig
src/gossip/service.zig
src/net/socket_utils.zig
src/utils/tar.zig
src/utils/thread.zig

Starts work towards #119 & #120.
More details in the commits.

improvement(gossip,tar): Work towards improving thread management

---

src/cmd/cmd.zig
src/gossip/fuzz.zig
src/gossip/service.zig

This involves passing the "message allocator" as a more general "table allocator" at the initialization site of gossip service, to allow the gossip table to properly free the data with the right allocator.
Merging this should be high priority, because currently there is a panic in a currently very reachable set of codepaths, which only manifested when testing on mainnet.

fix(gossip): Fix invalid free

---

src/gossip/pull_response.zig
src/gossip/service.zig

This will allow easier diagnosis of #157. Also just seems useful to be able to plug in any PRNG.

improvement(gossip): Take random interface param and log bad seeds for `filterSignedGossipDatas`

---

src/accountsdb/accounts_file.zig
src/accountsdb/db.zig
src/accountsdb/index.zig
src/accountsdb/snapshots.zig

This provides stronger type safety guarantees than the typedef, and makes the association between code that works with `FileId`s clearer.
Also enhances `AccountFileInfo.validate` by annotating it with an explicit error set, and adding a check to ensure the file id is within the range described by the comment.

improvement(accountsdb): Make `FileId` a typed alias, & enhance `AccountFileInfo.validate`.

---

build.zig
build.zig.zon
src/cmd/cmd.zig

Couldn't identify any issues with just using zig stdlib's version of `getAddressList`, it appears to work better internationally, and using it means we have one less dependency (we get rid of zigdig).
I also took the time to replace the string buliding with a formatting function for the log, and used an adapted ArrayHashMap(void, void) hash map to deduplicate entrypoints (on that note, should we issue a warning for duplicate domains or anything like that?).

fix(cmd): DNS improvements

---

build.zig

* unit_tests -> unit_tests_exe reflects the naming convention of all the other artifacts, alongside unit_tests_run -> unit_tests_exe_run.
* Don't make all run steps depend on the global install step, because doing so makes running any single artifact recompile every single artifact, which is a waste of time during iteration.

improvement(build.zig): More consistent name & don't depend on install to reduce redundant compilation times

---

src/core/hash.zig

Follow up to https://github.com/Syndica/sig/pull/162

fix(core): Make `core.Hash` extern to guarantee its layout

---

src/shred_collector/service.zig
src/shred_collector/shred.zig
src/shred_collector/shred_processor.zig
src/shred_collector/shred_tracker.zig
src/utils/collections.zig

I've been seeing SlotUnderflow get logged occasionally as an unhandled error in the shred processor. Service manager ends up restarting it, so it's not fatal, but it's not ideal to rely on this, for multiple reasons, such as:
- this underflow is not a problem and should not disrupt or log anything
- any shreds that have already been drained from the channel, but not processed, are discarded without being processed
- the error log message is overly generic
- restarting the loop has a performance penalty
This bug was introduced because I added `tracker.skipSlots` which was looking backwards from the shred's slot in order to skip the slots behind it. it's running into the underflow error when the slot has already been skipped. In that case it should just move on without complaining, because …

fix(shred-collector): SlotUnderflow bug, and generally improve error handling in shred processor

---

src/accountsdb/db.zig
src/accountsdb/download.zig
src/cmd/cmd.zig
src/net/net.zig

This field is effectively already used as a parameter, this just makes it impossible to accidentally access it as a field before it's initialized, or after it's done being useful.
Also improve the code for creating and using the disk memory allocator.

refactor(accountsdb): Make the `fields` field optional, and validate that it's non-null before working with it

---

src/accountsdb/snapshots.zig

```sh
zig build run -- validator --entrypoint entrypoint2.devnet.solana.com:8001
```
```
thread 6348676 panic: integer overflow
/Users/drew/mine/code/sig/src/accountsdb/snapshots.zig:729:18: 0x1046c296b in validate (sig)
slot -= 1;
^
/Users/drew/mine/code/sig/src/cmd/cmd.zig:502:30: 0x1046c3c97 in validator (sig)
try status_cache.validate(gpa_allocator, bank_fields.slot, &slot_history);
^
/Users/drew/.cache/zig/p/1220c008492d9460c3be2b209600a948181e6efb3bf0d79a1633def499632e708f4b/src/parser.zig:24:18: 0x10462b7fb in run (sig)
return action();
^
/Users/drew/mine/code/sig/src/cmd/cmd.zig:864:19: 0x10462b67b in run (sig)
return cli.run(app, gpa_allocator);
^
/Users/drew/mine/code/sig/src/main.zig:21:16: 0x10462d24b in main (sig)
try cmd.run();
^ …
```

fix(accountsdb): status cache integer overflow when slot = 0

---

src/gossip/data.zig
src/gossip/message.zig
src/gossip/pull_request.zig
src/gossip/shards.zig
src/gossip/table.zig

Currently - for some types, only a permalink to its Rust equivalent is added as the comment.
In this PR, the name of the Rust equivalent type is also added in the comment to improve searchability.
Note: This PR resolves the issue mentioned in https://github.com/orgs/Syndica/projects/2/views/5?pane=issue&itemId=60466783.

docs(gossip): add the name of the rust equivalent type in the comments

---

src/net/net.zig

Replacing this with a similar approach outlined in the IPv4 parsing would be good for performance reasons, but given that this is a fallback in the first place maybe this approach is fine for now. If this way is a non-starter, I could take another go to try and make it cleaner / faster. Tried following contributions document and the example of the rest of the code in the codebase.
Essentially, I saw a TODO and thought this might be someplace where someone without much experience with the codebase as a whole could contribute something of relative substance.

feat(net): initial go at IPv6 parsing

---

src/bloom/bloom.zig
src/gossip/active_set.zig
src/gossip/data.zig
src/gossip/fuzz.zig
src/gossip/pull_request.zig
src/gossip/pull_response.zig
src/gossip/service.zig

For all the functions that are directly generating random numbers using a PRNG (where the seed used is `std.time.milliTimestamp`), a `std.Random` interface parameter has now been added which generates the random numbers instead. This is done to decouple the actual PRNG implementation and its seed from the function.
This decoupling is useful during testing since we can easily find out the specific PRNG seed used when the function fails.
The functions that were modified are:
- Bloom.random()
- GossipPullFilterSet.consumeForGossipPullFilters()
- GossipService.buildPullRequests()
- NodeInstance.init()
- ActiveSet.rotate()
Note: This PR attempts to resolve issue https://github.com/Syndica/sig/issues/176.
**Update(27 Jun 2024):** Based on @InKryption's review, a `std.Random` interface parameter …

improvement(gossip): replace all uses of `std.time.milliTimestamp` as a PRNG seed with a `std.Random` interface parameter

---

src/cmd/cmd.zig
src/cmd/config.zig

The validator was silently crashing most of the time due to the non-existence of the accountsb/snapshot directory. Refactored a couple other adjacent things.

fix(cli): amend CLI details & fix crash

---

src/accountsdb/snapshots.zig
src/bincode/arraylist.zig
src/bincode/bincode.zig
src/bincode/shortvec.zig
src/bincode/varint.zig
src/bloom/bloom.zig
src/core/transaction.zig
src/gossip/active_set.zig
src/gossip/data.zig
src/gossip/service.zig
src/gossip/table.zig
src/lib.zig
src/version/version.zig

**Overview**
1. Rename pruned_peers to peers in ActiveSet
2. Fix shouldTrim method in GossipTable so we trim when 90% capacity is reached, not 110%
3. Address TODO in src/bincode/bincode.zig
4. Update imports in modified files to fit new import style guide (draft here):
**Import Style Guide (Draft)**
Declare imports in the following groups, separated by a newline.
1. group @import's
2. group namespace aliases
3. group struct aliases
4. group function aliases 
5. group constant aliases
If it improves clarity, split group's into Sig and External imports / aliases.
**Namespaces and Aliases**
In my mind, it would be useful to establish some sort of convention for how we alias namespaces, structs, methods etc. For example in service.zig we access structs and methods from src/gossip/data.zig …

refactor+fix(gossip):  update naming in active set and fix table trim condition

---

docs/CONTRIBUTING.md

Implement style guide roughly defined here https://github.com/Syndica/sig/pull/184
Note:
Consideration of using local imports within modules so that lib files expose only the public interface of a module
Could use the following approach for imports  (src/gossip/service.zig)
const sig = https://github.com/import("../lib.zig");
const lib = struct {
const table = https://github.com/import("table.zig");
const active_set = https://github.com/import("active_set.zig");
};
const SocketAddr = sig.net.SocketAddr;
const ServiceManager = sig.utils.service_manager.ServiceManager;
const GossipTable = lib.table.GossipTable;
const HashTimeQueue = lib.table.HashTimeQueue;
const AutoArrayHashSet = lib.table.AutoArrayHashSet;

feat(docs) Add import style guide

---

build.zig.zon
src/accountsdb/accounts_file.zig
src/accountsdb/db.zig
src/accountsdb/index.zig
src/accountsdb/readme.md
src/accountsdb/snapshots.zig
src/bincode/arraylist.zig
src/bincode/bincode.zig
src/bincode/int.zig
src/bincode/list.zig
src/bincode/optional.zig
src/bincode/shortvec.zig
src/bincode/slice.zig
src/bincode/varint.zig
src/bloom/bit_vec.zig
src/bloom/bloom.zig
src/cmd/cmd.zig
src/cmd/config.zig
src/core/leader_schedule.zig
src/gossip/message.zig
src/gossip/service.zig
src/shred_collector/shred.zig
src/utils/fmt.zig
src/utils/lib.zig
src/utils/tar.zig
src/utils/types.zig

Note: there are a number of auxiliary changes that were made in the course of this change set as a result of running into and needing to fix issues, mainly involving manual testing, and minor amendments, alongside some small refactors.
This implements the most fundamental building blocks for generating snap shot tar files, and sets up our infrastructure proper for then compressing said tar files into zstd archives. At present none of this is plugged in anywhere, it's just unit tested. As such, this code will still probably need to experience much evolution as we sculpt the architecture of consensus and any other related components.
Edit:
the scope of this PR increased from the initial goal of generating snapshots, to include indirect but auxiliary improvements to lay the infrastructure …

feat(accountsdb): Generate snapshots, fix UAF, improve bincode

---

src/accountsdb/accounts_file.zig
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/snapshots.zig
src/rand/rand.zig
src/sync/mux.zig

Incremental snapshots as a whole still aren't ready for the manager loop, but this does set up the basic infrastructure required to flesh them out later, giving us a working base for generating incremental snapshots.
This also includes improvements to full snapshot generation (both in service of incremental snapshot generation and in general).
At the time of writing, I still need to check that it hasn't broken fuzz testing with full snapshots on; this removes the explicit fuzz testing in the fuzz loop, but it does generate full snapshots in the manager loop.

feat(accountsdb): incremental snapshot generation

---

.github/workflows/check.yml

Mlugg's `setup-zig` will cache the global directory for us, where the `rocksdb` dependency resides. This will negate the increased CI times from 3c8129697a6eb3e7e69366047547244c46a8b0cc.
I also took the opportunity to remove the `rocksdb` fix, since I don't believe it's needed anymore.

fix(ci): switch to using `mlugg@setup-zig` for better caching of `rocksdb`

---

build.zig
src/sync/thread_pool.zig

Also correct the `@fence` to a tsan-aware fence.
We can start chipping away at the races one at a time. Maybe one day we could run the CI with tsan on. This fixes at least one reported race, since afaik `tsan` can't see that acquire fence without giving it the hint.

feat(build): add an option for enabling `tsan` in the test runner

---

.gitignore
src/accountsdb/bank.zig
src/accountsdb/db.zig
src/accountsdb/download.zig
src/accountsdb/fuzz_snapshot.zig
src/accountsdb/snapshots.zig
src/cmd/cmd.zig
src/cmd/config.zig
src/core/leader_schedule.zig
src/geyser/core.zig
src/utils/directory.zig

- adds a new cli-flag `-n` which allows you to use pre-defined entrypoints (eg, `gossip -n testnet` will run gossip with the default testnet entrypoints) 
- adds a new `buildFullSnapshot` method on accounts-db to create a snapshot with many reasonable defaults 
- improve snapshot downloading log statements + error handling
- fix bug in `SnapshotFields.collapse` (src/accountsdb/snapshots.zig)
- add a few new commands to cli - `snapshot-create` which creates a snapshot, `print-manifest` which loads and prints some info on a manifest

fix(accounts-db): random fixes

---

src/gossip/data.zig

In places where the gossip data variants are enumerated, it is possible to modify a variant without updating the other places.
This Pr makes it such that, doing that would now be a compile error.

improvement(gossip): Add more type safety to tracking gossip data tags

---

.github/workflows/check.yml
scripts/parse_kcov.py

Before we weren't checking if the `max_len` file we were considering was going to be in the set of files under `sig/`.
This cleans the script up a bit :).
Now we can actually see the file paths in the CI for the kcov report printer!
Also now we download kcov from a binary instead of building it each time. I don't really see why we would need to build it, so this will speed up the CI quite a lot for now.
```
src/time/estimate.zig ---       0.00%
src/trace/logfmt.zig ---       0.00%
src/shred_collector/shred_receiver.zig ---       0.00%
src/trace/level.zig ---       0.00%
src/prometheus/http.zig ---       0.00%
src/utils/lazy.zig ---       0.00%
src/shred_collector/shred_processor.zig ---       0.00%
src/shred_collector/shred_verifier.zig ---       0.00%
src/gossip/dump_service.zig --- …
```

fix the `parse_kcov.py` script to correctly calculate the max length

---

src/geyser/core.zig
src/utils/allocators.zig
src/utils/lib.zig

This implements thread safety within RecycleFBA by acquiring and releasing the lock in the alloc, free, and resize functions. Code that uses the allocator no longer needs to directly access the mutex in the RecycleFBA
Thread safety is configurable using the same approach as the GPA. The type takes a comptime config parameter. Thread safety is on by default if multithreading is supported by the platform.
pinging @dadepo for visibility since he is also using this allocator in his branch.

feat(allocators): RecycleFBA: configurable inherent thread safety

---

src/accountsdb/db.zig
src/accountsdb/index.zig
src/accountsdb/swiss_map.zig
src/utils/allocators.zig

Follow-up to #220.
Before this change set code was copying RwMux(AccountReferenceHead)s, rendering it entirely thread-unsafe, since the actual rwlocks were not being respected.
After this change set, each account reference head is simply stored as is, and is considered to be under the same lock as the bin in which it lives - this is a similar fix as was applied to AccountsDB's file map.
This also comes with a myriad of improvements to AccountIndex which simplify the code dealing with the linked-list component of account references.

fix(accountsdb): AccountRefHead thread-safety

---

.github/workflows/check.yml
scripts/remove_unused.py

This adds `--check` and `--verbose` flags to remove_unused.py, and uses `--check` in CI.
- `--check`: don't actually edit the files, and instead provide a more helpful output including the line number and the actual line of code that should be removed.
- `--verbose`: log filenames that had 0 unused imports (previously this was the default behavior, but now it's disabled by default)
```bash
python scripts/remove_unused.py --check src
```
```
Found 2 unused import(s) in src/core/pubkey.zig:
75 | const ChaChaRng = sig.rand.ChaChaRng;
76 | const Epoch = sig.core.Epoch;
Found 3 unused import(s) in src/core/entry.zig:
4 | const Pubkey = sig.core.Pubkey;
5 | const Epoch = sig.core.Epoch;
6 | const AccountInFile = sig.accounts_db.accounts_file.AccountInFile;
total unused found: 5
``` …

ci(scripts): better remove_unused.py output

---

src/blockstore/blockstore.zig

The `blockstore` folder has already been renamed to `ledger`. Somehow, `blockstore/blockstore.zig` snuck its way back in the repo. It's no longer in use, since `ledger/blockstore.zig` has replaced it. So this file should simply be deleted.

fix(blockstore): remove stray blockstore file

---

src/accountsdb/snapshots.zig
src/bincode/arraylist.zig
src/bincode/bincode.zig
src/bincode/hashmap.zig
src/bincode/list.zig
src/bincode/optional.zig

This takes all the custom logic from bincode.read and bincode.write that was written for hashmaps and arraylists, and it moves it to functions that return it as a FieldConfig in bincode/hashmap.zig and bincode/arraylist.zig. This `hashmap` field in FieldConfig is no longer needed, since this can be specified directly instead.
The `getConfig` function automatically applies the hashmap and arraylist FieldConfig for compatible types that don't have another config already. Long term there may be a better or more flexible way to include standard configs (maybe in Params?) but this was the easiest place to put it for now.

refactor(bincode): extract hashmap and arraylist code to field configs

---

metrics/grafana/dashboards/gossip_metrics.json
src/cmd/cmd.zig
src/gossip/fuzz_table.zig
src/gossip/service.zig
src/gossip/table.zig

new gossip metrics include: 
```
// inserting push messages stats
push_message_n_invalid_shred_version: *Counter,
push_message_n_new_inserts: *Counter,
push_message_n_overwrite_existing: *Counter,
push_message_n_old_value: *Counter,
push_message_n_duplicate_value: *Counter,
push_message_n_timeouts: *Counter,
// inserting pull response stats
pull_response_n_invalid_shred_version: *Counter,
pull_response_n_new_inserts: *Counter,
pull_response_n_overwrite_existing: *Counter,
pull_response_n_old_value: *Counter,
pull_response_n_duplicate_value: *Counter,
pull_response_n_timeouts: *Counter,
```
this gives new insight into whats happening to the messages we receive (mainly pull responses, since the gossip client doesnt seem to get many push messages)
this pr also includes a few bug fixes: 
- …

feat(gossip): improved metrics

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/readme.md
src/cmd/cmd.zig
src/utils/allocators.zig

Makes the allocator a bit smarter, able to resize allocations, and the ability to delete the associated file when freeing an allocation. Also removes the `init` method in favor of simply initializing the struct; as well, removes the `deinit` method, since there's nothing left to cleanup now that the files are deleted after properly freeing allocations.
Also adds a couple tests.

improve(allocators): improve DiskMemoryAllocator

---

metrics/grafana/dashboards/gossip_metrics.json
src/gossip/service.zig

closes #288
This gives us a 'packets/second' metric that should be more useful. Any lags in processing messages will be reflected in the channel length rather than the slope of the packets counter.
The new counter looks like this:
If there are any delays in processing, the length of the channel will go up:

improve(grafana): use rate for the packet info counter

---

src/accountsdb/db.zig
src/gossip/dump_service.zig

refactor: replace byte-slice Dir paths with Dir handlers

---

build.zig.zon

Lets me take advantage of https://github.com/Syndica/zstd.zig/commit/c6cde4f358a394dd0f332e873ae49d5b6f0dad4a - this is not so much intended for direct usage in final code, but to allow me or anyone else to directly interact with the raw C bindings in order to experiment directly in the sig codebase, in order to better discover if there are any missing abstractions or missed opportunities.

update(build.zig.zon): Update the zstd dependency

---

src/accountsdb/db.zig
src/utils/thread.zig

Extracted from some of my experimentation; doesn't appear to cause any measurable performance impact, reduces allocations (the total amount allocated will likely be similar since it's adding more metadata to the thread metadata), and overall seems to simplify and improve the code quality in my opinion.
Also resolves a TODO with a fairly simple solution.

refactor(thread): Make `spawnThreadTasks` use a wait group & replace task params with `TaskParams` struct

---

src/trace/logfmt.zig

This fixes a logic bug that I introduced in the logger pr. The bug is that string fields are formatted incorrectly. `[]const u8` ends up being formatted as `{any}` instead of `{s}`.
This branch of the if-else will actually never execute because it has a redundant condition with the first branch. It's just not supposed to have that condition. I think I copy and pasted it by mistake.

fix(trace): incorrectly logging string fields

---

src/prometheus/variant_counter.zig

When running the shred collector, sig panicked due to an index out of bounds error at the line of code edited in this pr.
The array index is supposed to be offset from the actual integer representation to reduce binary size. It's correctly offset during init but incorrectly offset when observed. This results in an index out of bounds error if the integer representation of the error/enum is larger than the difference between the min and max integer representations for that set. Otherwise it just results in incorrectly reported metrics.
This fix applies the offset during observations, to be consistent with the offset used during initialization.

fix(prometheus): index out of bounds error in variant counter

---

src/trace/entry.zig
src/trace/log.zig
src/trace/logfmt.zig

This changes the `Entry` type so that it directly contains any logger "fields" within the struct as normal struct fields instead of allocating strings repeatedly along the way. This unlocked some simplifications to the code and allows the code to be more organized. It also reduces allocations which theoretically could have a performance benefit.
There are no meaningful changes to the logger api. You still use it in exactly the same way as before. Note that I haven't changed anything outside the `trace` module. While it's true the Entry type is different, the entry type is not intended for use outside the logger, so it's not really an api change in my opinion.
The basic unchanged idea of the logger is that you call some method like `logger.info()` and then you're supposed to directly chain …

refactor(trace): reimplement Entry to reduce allocations and simplify code

---

src/ledger/shred.zig

The merkle proof size in bytes is the number of entries (`variant.proof_size`) times the number of bytes per entry (`merkle_proof_entry_size`). Currently we have it adding these two values instead of multiplying, which is a bug.

fix(ledger): retransmitter offset is incorrect due to merkle proof size being incorrectly calculated

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/cmd/cmd.zig
src/fuzz.zig
src/geyser/main.zig
src/gossip/fuzz_table.zig
src/trace/log.zig

The logger was being allocated 1 GB up front which seems like a mistake. If the logger doesn't work with 1 MB, that sounds like a bug
I also took out some explicit panics from functions that were already returning an error.

fix(trace): reduce logger memory consumption from 1 GB to 1 MB

---

docs/CONTRIBUTING.md

This codifies the conclusions reached in #304, as well as those reached in the discussions in and originating from #315.
The main additions are `Identifiers`/`Interfaces & Interface State`, and `Identifiers`/`Constants`.
While adding these, I also took the liberty of making some details more consistent, like removing the newline between a header and the first paragraph, rewording some other sections to be more accurate, and removing some unnecessary detail.
I also split up some short paragraphs into separate lines which were a single continuous line before, which made it easier to visualize all the information in a single screen.

refactor(docs): Update, rephrase & improve CONTRIBUTING.md

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/index.zig
src/accountsdb/lib.zig
src/accountsdb/readme.md
src/accountsdb/swiss_map.zig
src/benchmarks.zig
src/cmd/cmd.zig
src/cmd/config.zig
src/core/hash.zig
src/geyser/core.zig
src/geyser/main.zig
src/trace/log.zig
src/utils/allocators.zig

improved naming of structs/vars after taking a look back over the code
main changes were made to the index: 
- move disk_allocator into AccountIndex
- move bin logic into `ShardedPubkeyRefMap` and rename 'bins' to 'shards'
- improve reference allocator definition (now is an enum, Ram or Disk with a corresponding config)
- rename maps to be more key-value specific -- (ie, reference_memory -> slot_reference_map)
other smaller changes include:
- improve recycle_fba allocator config to be more specific
- improve hash equality check
- support single-threaded hash calculation

feat(accountsdb): improved struct/var naming

---

src/ledger/blockstore.zig
src/ledger/database/hashmap.zig
src/ledger/database/interface.zig
src/ledger/database/lib.zig
src/ledger/database/rocksdb.zig
src/ledger/lib.zig
src/ledger/schema.zig
src/ledger/shred_inserter/lib.zig
src/ledger/shred_inserter/merkle_root_checks.zig
src/ledger/shred_inserter/recovery.zig
src/ledger/shred_inserter/shred_inserter.zig
src/ledger/shred_inserter/slot_chaining.zig
src/ledger/shred_inserter/working_state.zig
src/ledger/tests.zig

This PR only changes the organization of files in the ledger, and likewise the imports. I moved some files from the ledger folder into two new subfolders: `database` and `shred_inserter`.
I've been finding it hard to make sense of the number of files in the ledger. I would look at the list of files and struggle to answer questions like, "Which files are for inserting shreds?" This is not a good sign, since I'm the one who wrote it. So I think it's appropriate to add a bit of structure to show how some of these apparently disparate files are actually intimately linked.
For example, there is one function `insertShreds` which is the sole entrypoint for all the code within 5 files in the ledger. Those files were scattered throughout the ledger folder and it wasn't totally clear what their …

refactor(ledger): organize into folders

---

src/cmd/cmd.zig
src/cmd/config.zig

The gossip cli has these two options:
```
--gossip-host <Gossip Host>           
-p, --gossip-port <Gossip Port>      
```
`--gossip-host` requires that the port is set. 
This begs the question if `--gossip-host` is passed and also `--gossip-port`, which value should be used as the port? 
Current behaviour is that the port passed with the host is always ignored, and `--gossip-port` is used if set, if not it defaults to `8001`.
Given the port passed with the host, IMO should be more authoritative, this PR tries to use that first, if not then it defaults to 
`--gossip-port`, and if that is not set, defaults to `8001`.

improve(cli, gossip): get gossip port from host if given, fallback to gossip port

---

build.zig.zon
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/sig.zig

- fix how duplicate pubkeys were tracked in the fuzzer
- cache seems to be broken:
```
reading account from cache: core.account.Account{ .lamports = 19, .data = { 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170 }, .owner = 11111111111111111111111111111111, .executable = false, .rent_epoch = 0 }
thread 27871801 panic: found account 3jtiL1JbjZEA2PKEvZi2c2j4PYQfCpifE6qRt3SQgKbK with different data: tracked: { 61, 126, 251, 93, 163, 58, 46, 40, 37, 234, 17, 105, 182, 209, 28, 195, 70, 69, 75, 183, 45, 67, 51, 55, 231, 176, 188, 184, 32, 220, 222, 219 } vs found: { 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, …
```

fix(accountsdb): fuzz testing

---

src/ledger/meta.zig
src/ledger/reader.zig
src/ledger/shred.zig
src/ledger/shred_inserter/merkle_root_checks.zig
src/ledger/shred_inserter/recovery.zig
src/ledger/shred_inserter/shred_inserter.zig
src/ledger/shredder.zig

closes #212
- Moved shred fields out of GenericShred struct into each respective shred struct: DataShred and CodeShred.
- Anywhere that fields from `fields` were being accessed, switched it to get the fields directly from the shred struct. so `shred.fields.common` is now `shreds.common`
- For any usages of methods in GenericShred via `fields` outside shred.zig, analogous methods were added to DataShred and CodeShred to serve the same purpose. this is in service to the point above, so things like `shred.fields.merkleRoot()` are now `shred.merkleRoot()`
- All the methods from GenericShred are now just functions in a private namespace called `generic_shred`. other shred structs that used to call `self.fields.function()` now call `generic.function(self)`
- Renamed `default` initializers in …

refactor(ledger): flatten shred field nesting

---

src/trace/log.zig

fixes #334 
The logger was hitting OOM because it never freed the messages after logging them.

fix(trace): log message memory leak

---

src/accountsdb/cache.zig
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/cmd/cmd.zig
src/rand/rand.zig

- makes AccountsCache configurable
- introduces pseudo-random  weighted sampling of accounts using the [Alias Method](https://en.wikipedia.org/wiki/Alias_method) (before this code accessed every account once in order).
- adds a small optimisation to AccountsCache.CachedAccount

perf(accountsdb): improve benchmarking

---

src/ledger/transaction_status.zig
src/rpc/client.zig
src/rpc/types.zig

- log the RPC client version on `init`
- improve getClusterNodes return type to have all fields (renamed to match anza `RpcContactInfo`)
- add `getVersion` rpc call 
- fix `getAccountInfo` value to be optional
- add error type for `getSignatureStatuses` to fix parsing error

fix(rpc): return types

---

src/benchmarks.zig
src/bincode/benchmarks.zig
src/bincode/bincode.zig
src/bincode/int.zig
src/core/account.zig
src/core/entry.zig
src/core/pubkey.zig
src/core/transaction.zig
src/crypto/base58.zig

The first commit adds a benchmark to serialize Entry. The second commit adds an optimization to bincode to directly copy bytes instead of attempting to serialize/deserialize them as individual integers. This speeds up Entry de/serialization by 3-4x.
before:
```
Benchmark        Iterations    Min(ns)    Max(ns)   Variance   Mean(ns)
-----------------------------------------------------------------------
serializeEntry       200000       1083      70417     191263       1367
---
deserializeEntry     200000       2250      60291     116981       2515
```
after:
```
serializeEntry       200000        250      14959       8130        350
---
deserializeEntry     200000        666      21666      12248        784
```

perf(bincode): faster de/serialization of raw bytes

---

src/ledger/shred.zig
src/ledger/shred_inserter/merkle_root_checks.zig
src/ledger/shred_inserter/shred_inserter.zig
src/ledger/shred_inserter/working_state.zig
src/shred_collector/shred_receiver.zig
src/shred_collector/shred_verifier.zig

Previously, backwards merkle root chaining checks were:
- ignoring the actual result of the check
- always marked it as a duplicate (as if the check failed)
- always returned true (as if the check succeeded)
- comparing chained root to chained root, which is wrong. it should be chained to actual root
consolidate common chaining logic into single function "checkAndReportChaining"
Improve dependency management by:
- organizing merkle root check functions into a struct since they all share some common dependencies. this simplifies the function signatures and keeps things standardized and consistent
- utilizing working stores.
- this is better than passing down the granular transitive dependencies (database and hashmap) separately because it clarifies what this code actually needs. all it …

fix(ledger): backward merkle root chaining bugs

---

src/core/signature.zig
src/gossip/message.zig
src/gossip/ping_pong.zig
src/ledger/database/hashmap.zig
src/ledger/database/interface.zig
src/ledger/database/rocksdb.zig
src/ledger/shred.zig
src/shred_collector/repair_message.zig
src/shred_collector/shred_verifier.zig

The previous strategy was... interesting, to put it mildly. It should be noted that putting `test` blocks inside of generic structs, *is* allowed. 
Also removed some usages of `catch unreachable` that actually were reachable.

test(ledger): cleanup database testing

---

src/shred_collector/shred_receiver.zig

The following metrics were not being incremented:
- shred_receiver_received_count
- shred_receiver_satisfactory_shred_count
This pr fixes it by incrementing them in the appropriate places.

fix(shred-collector): shred receiver metrics not being counted

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/index.zig
src/cmd/cmd.zig
src/cmd/config.zig
src/common/merkle_tree.zig
src/utils/allocators.zig

feat(accounts-db): change reference pointers to indexes

---

scripts/view_bench.py
src/benchmarks.zig

- colors werent working as expected on the script 
- f_min/f_max were not in the correct order for output

fix(benchmarks): script colors + print results

---

.github/workflows/check.yml
build.zig
build.zig.zon
src/ledger/benchmarks.zig
src/ledger/blockstore.zig
src/ledger/cleanup_service.zig
src/ledger/database/hashmap.zig
src/ledger/database/interface.zig
src/ledger/database/lib.zig
src/ledger/database/rocksdb.zig
src/ledger/reader.zig
src/ledger/result_writer.zig
src/ledger/shred_inserter/merkle_root_checks.zig
src/ledger/shred_inserter/shred_inserter.zig
src/ledger/shred_inserter/working_state.zig
src/ledger/tests.zig
src/tests.zig
src/utils/allocators.zig

I broke up the lmdb pr #352 into two prs: this one and #373. This PR contains all the changes from #352 *except* for adding support for lmdb. I stripped out lmdb because it has a bug that I'm not sure how to fix yet. I'd like to get these improvements merged before figuring out lmdb.
-----------------------------------
This adds a build option to customize the database backend, for example:
```bash
zig build -Dblockstore-db=lmdb
```
RocksDB remains the default for now.
For any build, only the necessary dependencies will be compiled. For example, if you specify `-Dblockstore-db=hashmap`, then rocksdb will not be built.
A few bugs were uncovered in the hashmap db when testing the databases more strictly, so I fixed those in here as well.
I also upgrade the rocksdb library because it had an …

feat(ledger): user-selectable db, hashmapdb fixes, add tests, safer memory management

---

build.zig.zon

This upgrades rocksdb to a new commit from our fork of rocksdb. That commit includes some fixes, and upgrades rocksdb from 9.5 to 9.7.
----
Normally, I build sig for my work machine, which is a macbook, and it builds fine. I tried to build sig on my personal laptop and my desktop, and it did not build on either system. Both are running linux with intel cpus (tiger lake and arrow lake).
There are two errors. Both are failures to build rocksdb.
----
The first error is due to incorrect syntax from our commit to our fork of rocksdb.
```
/home/drew/.cache/zig/p/1220dc54736c65c61ee181cd2716db055cb78131ebed2b88ccf4733f43d35ac39eeb/port/lang.h:79:16: error: extra tokens at end of #ifdef directive
#ifdef __AVX__ && (_MSC_VER)
^
/home/drew/.cache/zig/p/1220dc54736c65c61ee181cd2716db055cb78131ebed2b8 …
```

fix(rocksdb): `zig build` fails on linux intel systems

---

src/utils/allocators.zig

- see doc comment on struct to understand its usage
- this new allocator is specifically for the account index and is built with that in mind (vs a more general purpose allocator) 
- it doesnt even support the .allocator interface because its very niche
- usage and more will be shown in the stack above (#382)

feat(allocator): add recycle buffer

---

.github/workflows/check.yml
src/benchmarks.zig

Improved benchmark filtering with an enum-based approach and added a help menu for available benchmarks.
These changes were pulled from #298 and full credit goes to @Rexicon226 
- Introduced a `Benchmark` enum to strictly type available benchmark options
- Added a `--help` flag that displays all available benchmarks
- Replaced string-based benchmark filtering with enum matching
- Updated error handling to show usage information for invalid benchmark names
- Modified logging messages to be more precise
1. Run `zig build benchmark -- --help` to view available benchmarks
2. Test individual benchmarks: `zig build benchmark -- [benchmark_name]`
3. Run all benchmarks: `zig build benchmark -- all`
4. Verify error handling by attempting to run an invalid benchmark name
The enum-based approach …

improve(benchmarks): better cli parsing

---

src/accountsdb/index.zig
src/utils/allocators.zig

Added persistence capabilities to AccountIndex by implementing save and load functionality for disk storage.
- add index field to both ref and ref-head structs
- Added `loadFromDisk` and `saveToDisk` methods to AccountIndex
- Modified AccountRef structure to handle serialization properly
- Added helper function `allocFilename` to DiskMemoryAllocator
- Added comprehensive tests for saving and loading account index state
- Run the new tests: "save and load account index state" and "save and load account index state -- multi linked list"
- Tests verify that account references and their relationships are properly preserved when saving to disk and loading back
To enable persistence of account index data between program runs, allowing the system to maintain state across restarts and reducing …

feat(accountsdb): support index save/load

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/index.zig
src/cmd/cmd.zig
src/cmd/config.zig
src/utils/allocators.zig

- Added `should_fastload` and `save_index` parameters to AccountsDB loading functions
- Implemented new `fastload` function to quickly load account files and index from disk
- Added error handling for missing fast load files
- Introduced two new CLI options:
- `--fastload`: Enables fast loading of AccountsDB
- `--save-index`: Saves account index to disk for future fast loading
1. First run with `--save-index` flag to save the account index state
2. On subsequent runs, use `--fastload` flag to quickly load the AccountsDB
3. Verify that loading times are significantly reduced when using fast load
4. Test error handling by attempting to fast load without first saving the index
Loading the AccountsDB, particularly the account index, is a time-consuming operation. This change improves startup …

feat(accountsdb): support fastload with cli options

---

src/cmd/cmd.zig

I was running into the panic
```
(base) ubuntu@ip-172-31-7-85:~/me/sig$ solana -ut leader-schedule | ./sig shred-collector -n testnet --leader-schedule -- --test-repair-for-slot $(solana -ut slot)
[cmd.cmd.AppBase] time=2024-11-26T10:57:18.540Z level=info metrics port: 12345
[cmd] time=2024-11-26T10:57:18.546Z level=info adding predefined entrypoint: entrypoint.testnet.solana.com:8001
[cmd] time=2024-11-26T10:57:18.615Z level=info adding predefined entrypoint: entrypoint2.testnet.solana.com:8001
[cmd] time=2024-11-26T10:57:18.690Z level=info adding predefined entrypoint: entrypoint3.testnet.solana.com:8001
[cmd] time=2024-11-26T10:57:18.698Z level=info entrypoints: { 35.203.170.30:8001, 139.178.94.143:8001, 139.178.94.143:8001 }
[cmd] time=2024-11-26T10:57:18.929Z level=info shred …
```

Shut down before deinit

---

src/accountsdb/download.zig
src/cmd/cmd.zig
src/gossip/active_set.zig
src/gossip/fuzz_service.zig
src/gossip/fuzz_table.zig
src/gossip/pull_request.zig
src/gossip/pull_response.zig
src/gossip/service.zig
src/gossip/shards.zig
src/gossip/table.zig
src/shred_collector/repair_service.zig
src/sync/mux.zig
src/turbine/turbine_tree.zig

- Moved GossipService allocation to heap with new `create()` function
- there were a random number of structs which were heap allocated, whereas others were not - this change puts everything on the stack, and uses the `create` method to make everything on the heap (which it should be due to the multi-threaded nature of gossip)
- Removed thread pool dependency from GossipTable initialization (was dead code)
- Removed unused echo server implementation (was dead code)
- ticket to add it back with working server [here](https://github.com/orgs/Syndica/projects/2/views/10?pane=issue&itemId=88750700)
- Added proper cleanup of muxes in GossipService deinit

refactor(gossip): improved init flow

---

build.zig

We should remove this code when we update to 0.14, where this feature detection is implemented properly in the underlying code used by the build system.
This will allow us to just `zig build` without needing to specify the CPU target for the time being.

fix(build): temporary fix to detect the M3 cpu by default

---

src/gossip/dump_service.zig
src/gossip/service.zig
src/net/quic_client.zig
src/net/socket_utils.zig
src/shred_collector/service.zig
src/sync/exit.zig
src/sync/lib.zig
src/transaction_sender/service.zig
src/turbine/retransmit_service.zig
src/utils/service.zig

Introduces a new `ExitCondition` union type to standardize thread exit handling across services.
- Added new `ExitCondition` union type with `ordered` and `unordered` variants
- Replaced direct atomic counter usage with `ExitCondition` abstraction
- Updated socket utilities and gossip services to use the new exit condition pattern
- Removed the `needs_exit_order` parameter from service spawning functions
- Simplified service manager interface by removing `spawnCustomIdx`

refactor(manager): change to explicit exit condition

---

.gitignore

We've been using the  `<folder-name>/` pattern in gitignore which can be problematic in some cases.
The first problem is that you may want to use the same name somewhere in the code. For example, "validator" should be an allowed name of a file or folder in the repository. We only want to block the `/validator` folder that's placed in the repository root to manage sig's local state. I think most of the things in .gitignore follow this pattern, so I've changed those to be absolute paths.
Also in cases where you want to block a folder from being committed at some absolute path, you probably don't want a *file* to be committed at that path either. That's where a trailing slash becomes a problem. It allows files to be committed at that path. So I've removed trailing slashes from most of that …

fix(gitignore): use absolute paths, remove unused

---

src/cmd/cmd.zig
src/net/net.zig

Moved socket address resolution logic from cmd.zig to net.zig and made it more reusable

fix(cmd): move resolveSocketAddr into net

---

src/accountsdb/db.zig
src/cmd/cmd.zig
src/rpc/lib.zig
src/rpc/server.zig
src/sync/thread_pool.zig
src/trace/log.zig
src/utils/io.zig

feat(rpc,accountsdb): RPC Server for snapshot propagation

---

src/benchmarks.zig
src/gossip/service.zig
src/ledger/benchmarks.zig
src/ledger/tests.zig
src/sync/channel.zig

- Changed time unit measurements from milliseconds to nanoseconds for gossip service benchmarks (was prev outputting either 0 or 1)
- Updated metric reporting to use maximum values instead of mean values (this should help reduce false positives for PR regressions)
- Increased max iterations:
- Gossip service benchmarks: 1 → 5 iterations
- Ledger benchmarks: 25 → 1,000 iterations
- Channel benchmarks: 20 → 500 iterations
- Added missing file close defer statement in ledger tests

fix(ci/cd): fix benchmarks metrics

---

build.zig
build.zig.zon

this also removes the hack to avoid ReleaseSafe

fix(ledger): use rocksdb version containing fix for llvm bug

---

.github/workflows/check.yml
src/cmd/cmd.zig

Disabled benchmark jobs in the GitHub Actions workflow.
Commented out both the `benchmarks` and `main_benchmarks` jobs in the GitHub Actions workflow file.

fix(ci/cd): tmp remove benchmarks

---

.github/workflows/check.yml

On the github runner, kcov is looking for libraries with version 38, but the system only has version 42. To get this working, I modified the workflow to hard link the files from 42 to 38. It's not an elegant fix, but currently all of our builds are failing, and this gets things working again. I created a ticket to look into this further: https://github.com/orgs/Syndica/projects/2/views/10?pane=issue&itemId=91539549

fix(ci): kcov dependencies on workflow runner

---

src/cmd/cmd.zig
src/core/leader_schedule.zig
src/ledger/shred_inserter/shred_inserter.zig
src/shred_network/service.zig
src/shred_network/shred_processor.zig
src/shred_network/shred_verifier.zig

This PR is a simple refactor that only renames the struct and stops using PointerClosure as an intermediary to define the struct.

refactor(leader_schedule): SlotLeaderProvider from PointerClosure to direct SlotLeaders struct

---

src/ledger/database/interface.zig
src/sync/lib.zig
src/sync/reference_counter.zig

Most of the logic from RcSlice is moved into RcBase, which is a minimal and less opinionated version of RcSlice that does not contain the length of the pointer. RcBase is intended to be more composable than RcSlice. The parent struct containing RcBase becomes responsible for determining the length of the pointer.
RcBase serves as the implementation for both RcSlice, which contains any number of items, and a new struct Rc, which contains exactly one item.
This change is a dependency of #461

refactor(sync): adapt RcSlice for single-item pointers

---

src/shred_network/turbine_tree.zig

Previously the gossip table lock was held for the entire function. It's only needed for this initial operation though.

perf(shred-network): reduce gossip lock hold time

---

src/sig.zig

To avoid the potential situation where code is refactored in such a way that compilation would succeed for a 32-bit target, but break at runtime due to assumptions in the way the code is written; the requirements for running an actual client are way beyond the capabilities of a 32-bit machine anyways, so this comes at no real cost.

enhance(all): Add global comptime assertion for target ptr size

---

build.zig
metrics/README.md
metrics/alloy/config.alloy
metrics/docker-compose.yml
metrics/grafana/datasources/datasource.yml

Pretty easy change, should be handy.
Has a good amount of detail, even in ReleaseSafe (thanks @Rexicon226 for suggesting to disable omit_frame_pointer).
If you're using docker desktop + macos, this won't work - the profiler won't be able to find your host's process.
(focused in on the gossip verification)
(focused further, into bincode)

feat(perf) Add continuous profiling support

---

metrics/grafana/alerting/alert_rules.yaml
metrics/grafana/alerting/contact_points.yaml
metrics/grafana/dashboards/gossip_metrics.json
src/gossip/service.zig

- make all gossip logs use the same scope (prev was different which means we werent tracking all error logs in grafana using filtering by scope)
- remove no data alerts using 'noDataState: KeepLast' in the alert rules (this was prev causing slack spams with incorrect values)
- add warning logs to grafana dashboard (realized well also want to see these)

fix(gossip): consistent scope + less alerts

---

build.zig
build.zig.zon
src/accountsdb/download.zig
src/cmd/cmd.zig

Written to retain equivalent or better download speed, and some enhancement to the behavior of output.
Now in the absence of C wrappers and callback indirection, I find the code to be much simpler to understand; I also simplified some of the logic in general.
I also took the liberty of now returning the resulting file, and propagating the resulting full and incremental snapshot file handles; for now this doesn't do anything, but in the future I would like to explore propagating them further in order to short-circuit the snapshot detecting logic - as in, making it unnecessary to scan the filesystem if we've just downloaded a snapshot pair.
Lastly, I tidied up a couple of other things, and publicized some decls that are depended on by a public function.

refactor(build,download): Remove curl dependency, replace with stdlib's http client

---

src/net/quic_client.zig

Agave does a hack where it precomputes the bytes of the certificate and public key because rustls doesn't support, something. I didn't exactly understand what it doesn't support.
I originally just copied straight from what agave was doing under the time pressure from the demo, however, now we can take a step back and fix up some of the uglier parts of the quic client. We're not using rustls, so we can confidently use the cleaner approach of constructing the certificate and keys using the boringssl API.
After a bit of fiddling around with the proper settings and realizing that `X509_gmtime_adj` returns an error if the value passed in is too large, this branch passes the transaction sender test and general usage by me.

improve(quic): remove x509 cert workaround in favor of openssl calls

---

build.zig

Basic changes:
* Adds no-bin.
* Renames 'run' to 'sig'.
* Re-organizes 'doc' step code.
* Re-organizes and makes some code more consistent.
* Step dependency graph rework:
An artifact's top level step now by default depends on the compile step, the install step, and the run step; the install and run steps can be individually disabled using `no-bin` and `no-run`. If both are disabled, there now will be no binary even compiled, allowing us to run semantic analysis without wasting time emitting a binary.

refactor(build): Add 'no-bin' & rework install/run behavior, rename 'run' to 'sig'

---

.github/actions/setup/action.yml
.github/workflows/check.yml
scripts/kcov_test.sh

This PR consolidates and caches the Sig artifacts created by our CI process to be shared across jobs. Before, each job would set up Zig and the associated cache, which would result in around 1.5GB of cache usage *per* job. This quickly spiraled out of control and ended up using hundreds of GBs of cache.
The changes here create 3 main jobs for building Zig. 
- `build` - This job builds Sig with and without TSAN, as well as a version of the tests which use the hashmap blockstore.
- `build-release` - This job builds Sig and the fuzzer in `ReleaseSafe`. Since all of the dependencies need to be built in `ReleaseSafe` as well, it has a separate cache to minimize duplication.
- `build-macos` - This job uses an ubuntu runner to build Sig targeting `aarch64-macos`. I've set this up as a separate …

feat(ci): cache build objects in between internal runs

---

.github/workflows/check.yml

With our increased usage of Graphite and just generally stacking PRs, I feel it'd be nice to run the CI on PRs that aren't at the very bottom of the stack. Sometimes concurrent reviews could be happening and changes to multiple PRs need to happen and be verified.

improve(ci): run CI on all pull requests, to better support stacking

---

src/accountsdb/download.zig
src/benchmarks.zig
src/cmd/cmd.zig
src/time/time.zig

current benchmarks get stuck trying to download a snapshot when the network isnt available -- this adds a timeout to the download attempt loop so we can break after some time and continue with the rest of the benchmarks

fix(ci): add timeout for snapshot downloads

---

src/cmd/cmd.zig
src/geyser/core.zig
src/geyser/main.zig
src/gossip/service.zig
src/net/lib.zig
src/net/socket_utils.zig
src/shred_network/repair_service.zig
src/shred_network/service.zig
src/shred_network/shred_processor.zig
src/shred_network/shred_receiver.zig
src/shred_network/shred_retransmitter.zig
src/shred_network/shred_verifier.zig
src/sync/channel.zig
src/trace/log.zig
src/transaction_sender/service.zig

Adds a Channel.SendHook concept to observe & override the behavior when a value is sent on a channel. It's used to notify a ResetEvent so that receivers can block on it without spinning. Exit flag is periodically checked by using `ResetEvent.timedWait(1s)` to block.

perf(channel): hooks to avoid spinning wait

---

metrics/grafana/dashboards/shred_collector_metrics.json
metrics/grafana/dashboards/shred_network_metrics.json
scripts/style.py
src/cmd/cmd.zig
src/cmd/config.zig
src/ledger/benchmarks.zig
src/ledger/readme.md
src/ledger/shred_inserter/shred_inserter.zig
src/shred_network/lib.zig
src/shred_network/repair_service.zig
src/shred_network/service.zig
src/shred_network/shred_processor.zig
src/shred_network/shred_retransmitter.zig
src/shred_network/shred_tracker.zig
src/time/time.zig

> ⚠️ *Note: most of the lines added in this PR are for the grafana dashboard*
This change was primarily motivated as a bugfix to deal with the issue that the shred collector would consistently get stuck at a certain slot and stop progressing.
What this means is that the shred tracker would think that it hasn't received all the shreds for a certain slot, and it would keep trying to repair that slot. Eventually it would lag so far behind that it would stop tracking any future slots ahead. This is because the shred tracker only worries about 1024 slots at a time. So the repair service would get into a degraded state with poor performance because it's looking at a ton of slot unnecessarily, and it would lose the ability to repair slots beyond a certain point. And our metrics in grafana would …

fix(shred-network): keep up with turbine

---

src/sync/channel.zig

Have a continous stream of senders (& maybe a receiver) then observe and report the channel throughput from the outside as nanoseconds per `send()`. This avoids senders completing early from only having to push a fixed amount of items, thus reducing contention (as they're out of the race) and randomizing throughput results.

perf(channel): fix contention in benchmarks

---

build.zig
build.zig.zon
src/cmd.zig
src/gossip/helpers.zig
src/net/echo.zig
src/prometheus/http.zig
src/prometheus/metric.zig

There are still some definite improvements/fixes to make to prometheus, like making it possible to tell it to exit gracefully.
Note: unlike in the echo case, I decided it probably wasn't worth the complexity of dispatching to a threadpool in the prometheus case - not actually even sure if it's worth it in the echo server case either, but I'm unaware of the particular requirements there, so I retained that behavior from httpz.
Also took the liberty of refactoring adjacent code.
There's a couple TODOs I'll resolve once the RPC server PR is also merged.

refactor(echo,prometheus,build): Remove our dependency on the httpz library

---

src/accountsdb/db.zig

was prev using the wrong hash during benchmarking validation - this pr fixes this

fix(benchmarks): incorrect hash in validation

---

build.zig
build.zig.zon
src/prometheus/http.zig

Currently, our prometheus server does not work. It has some issue with the way it responds to http requests. curl is able to get data from it, but prometheus itself is unable to connect to the server. I've tested this on my macbook and three linux boxes. Prometheus always has an error connecting to sig, likewise grafana doesn't get any data.
This is a big problem because it makes us blind to sig's internals while it's running. Manual end-to-end tests of things like gossip and the shred network are not practical until this is fixed, which means other tasks are being blocked by this bug.
This problem was introduced in #520 (remove httpz), so I've reverted the portion of that change which is relevant to prometheus. I haven't made any tweaks to the code, it's just a simple `git revert`.
After …

fix(prometheus): prometheus cannot connect to sig's metrics

---

src/accountsdb/db.zig
src/cmd.zig
src/geyser/benchmark.zig
src/geyser/core.zig
src/geyser/main.zig
src/prometheus/registry.zig
src/shred_network/repair_service.zig
src/utils/thread.zig

the main fix is to remove the waitgroups in accounts-db loading/validating so we can have errors propagate correctly. while doing this, i also noticed a bug in the homo-threadpool impl where `addOne` to existing tasks will cause re-allocs on existing thread state leading to a segfault. there was also some code in repair which would `join` the threadpool after a single schedule in a loop, which i assumed was a bug and fixed as well.
there was also a bug which tsan found where an allocator was used in the registry without a lock which i fixed as well.
this lead to another bug in tsan about registry init race conditions which was fixed in 553c8039.
- Refactored `spawnThreadTasks` to use a homogeneous thread pool instead of raw thread spawning
- Removed single-threaded code paths in favor of …

fix(adb/threadpool): remove waitgroups and fix segfault

---

build.zig
src/net/socket_utils.zig

Add an implementation of `socket_utils.SocketThread` using libxev. Disabled for now, but will be evaluated for use in the future.

perf(networking): add xev socket backend option

---

src/net/send_msg.zig

fixed up to match what I have upstream: https://github.com/ziglang/zig/pull/22635

fix(quic): correct the `msghdr_const` definition for the quic client

---

src/svm/elf.zig
src/svm/executable.zig
src/svm/sbpf.zig
src/svm/tests.zig
src/svm/vm.zig

This PR adds support for the PQR (product, quotient, remainder) extension which was described here: https://github.com/solana-foundation/solana-improvement-documents/pull/174.
Other than that, it's just a lot of tests to ensure the implementation of the extension is correct and matches other SVMs and a bit of cleanup in the ELF parser to replace more call sites with safe slicing, to prevent panics from invalid input.

feat(svm): PQR support

---

docs/docs/design-and-implementation/accounts-db.mdx
docs/docs/usage/run.mdx
src/accountsdb/readme.md
src/cmd.zig

The plan is to eventually move away from the zig-cli library we're using, but in the meantime it can't hurt to organize what we do have a bit better, to make the eventual switch easier to manage.
I manually checked that despite the slight re-ordering of some of the CLI options in this, no options were added to or removed from any commands.

refactor(cli): Some CLI options improvements and re-organization

---

build.zig
build.zig.zon
src/prometheus/http.zig

After delving into the packets via Wireshark, I saw that the packets were using HTTP 1.0. This seemed to cause some issues in Prometheus, still not sure exactly what. Seems to me like it's a Prometheus bug regarding how explicit keep-alive is handled, but have no idea. HTTP sucks!
@InKryption why did you explicitly use HTTP 1.0? Kinda confused there.
@dnut I think you're the one who was having issues, can you test it out? I could reproduce the same context timeout issue and it's gone on my machine.

fix(prometheus): remove httpz again and fix prometheus metrics

---

src/consensus/fork_choice.zig

Fork choice was using `std.log` instead of the logger it already has as a field. This switches to use its contained logger.

fix(consensus): use correct logger in fork choice

---

src/trace/level.zig
src/trace/log.zig
src/trace/logfmt.zig

The motivation of this change is to improve the readability of the logs without introducing a new formatter or breaking our existing compatibility with the logfmt standard.
Currently our log messages have the timestamp at the end of the line. This means the timestamp is in a different position for every log message, making it difficult to find when you're quickly skimming the logs.
This PR moves the timestamp to the beginning of the line. This is typically where loggers display the time, so it's what most people will be used to. 
Putting fixed-size items at the beginning of the line improves the alignment of the log contents, which makes the logs more organized and consistent. This helps the logs look a little more like a table instead of randomly scattered text. 
It's typical to look at …

feat(trace): Log output readability and consistency

---

.github/workflows/fuzz.yml

Makes it so that when we push a new commit to main, it triggers the CI setup in https://github.com/Syndica/sig-fuzz to run, build the bindings, bundle them, and send them off to FuzzCorp.

feat(ci): add sigfuzz CI dispatch

---

build.zig
src/bincode/bincode.zig
src/gossip/service.zig
src/net/socket_utils.zig

There's no blocking `sento` on BSD, so to throttle the buffer usage we're switching to the `XevThread` socket backend, otherwise, when the throughput is too high, we will drop packets with `NOBUFS`.

fix(socket): use XevThread for MacOS instead of PerThread

---

src/utils/service.zig

Linux only allows thread names up to 15 characters. If you exceed that limit, setting the thread name fails and the thread doesn't get a name. 
One solution is to just always name services with names under 15 characters. But those names are used in log messages and it would be nice to use more characters. So instead, I've just accepted that we're going to use longer names, and the thread name used by the kernel needs to be truncated to 15 characters.
I debated throwing a log message in here to warn about the name being truncated. But I think it's just clutter in the logs since we probably won't be trying to squeeze every name into 15 characters.

fix(service-manager): truncate overlong thread names

---

src/adapter.zig

I see this error pretty often in the logs:
```
time=2025-03-06T22:25:37.267Z level=error scope=adapter.RpcEpochContextService message="failed to refresh epoch context via rpc: error.EndOfStream"
```
This just means the connection was interrupted when downloading data from an rpc node. It's not a serious error, and a single occurrence does not imply any action needs to be taken by a human, so I added a retry mechanism. If this error happens, we just ignore it and try again, for up to three attempts. If all three fail, or any other error occurs, then we log an error.

fix(adapter): reduce error log noise from RpcEpochContextService

---

src/utils/service.zig

Previously when an error was returned by a service to service manager, it would log it as a warn message. I'm changing it to log as an error message. Originally it was actually an error, but it was changed to warn in this commit: f970d8b02cb58e16d05025eeef7bbdd467476b9a
If an error bubbles up to the service manager, it means the entire thread has crashed with an unhandled error. If there's anything we're going to log as "error" level in the logs, it should be these unhandled errors that crashed an entire thread and triggered the last-ditch generic error handler.

fix(service-manager): properly log errors

---

build.zig
build.zig.zon
src/prometheus/http.zig

Prometheus does not consistently get metrics from our metrics endpoint. The metrics are intermittent.
Also, the server often crashes due to errors. In #590 I added a wrapper to catch these errors and restart the server. But sometimes an error occurs that is handled, a server restart is attempted, but the server never responds to any http requests any more, so the metrics become completely inaccessible until sig is completely restarted. Usually this is caused by `error.BrokenPipe`
> Revert "fix(prometheus): remove httpz again and fix prometheus metrics (#555)"
> 
> This reverts commit 3502333aa0798734dd0b3384f9d41e47078a495a.
I understand the desire to eliminate unnecessary dependencies. In the grand scheme of things, eliminating httpz is not that important. Having a working metrics …

fix(prometheus): flaky metrics server

---

src/utils/io.zig
src/utils/lazy.zig

Add some more tests for some utils modules. Including a test that was missing from #596 (test a double peek).
While writing the unit-tests for Lazy, I corrected a small issue where the final result was not actually returned. Most likely this was dormant in the code because only `Lazy(void)` is currently used.

Add tests for lazy

---

docs/docusaurus/docs/code/geyser.md
docs/docusaurus/docs/code/gossip.md
docs/docusaurus/docs/usage/metrics.md
metrics/readme.md
src/cmd.zig
src/config.zig
src/geyser/readme.md
src/gossip/readme.md

this removes the "network" naming and changes it to be "cluster" which is more accurate -- this change (moving towards 'cluster') was already in effect but there were certain spots of inconsistencies -- this PR makes everything follow the "cluster" convention

fix: make "cluster" name unanimous

---

src/runtime/program/system_program/error.zig
src/runtime/program/system_program/execute.zig
src/runtime/pubkey_utils.zig

Native program errors should be enums, or implement a mapError method to map the error to the correct int according to Agave's analogous enum definition. If try semantics are required, using a map function with a switch may be the best option. Otherwise an enum is simpler.

refactor(runtime): change system_program error to enum

---

src/rpc/http.zig

After running `shred-network` for a few minutes, memory errors occur when freeing request strings in the rpc client, causing sig to exit. This is reliably reproducible and always happens within 5 minutes of startup.
```
> sig shred-network -c testnet
time=2025-03-18T15:07:59.133Z level=info scope=service_manager message="starting metrics endpoint"
time=2025-03-18T15:07:59.319Z level=info message="ip echo response" shred_version=64475  ip=35.203.170.30:8001 
time=2025-03-18T15:07:59.319Z level=info scope=cmd message="app setup" metrics_port=12345  identity=B2GvMLDug5Ni79RHp9WR6FpTsGp6i4ECThaZGLnv2Xke  entrypoints={ 35.203.170.30:8001, 139.178.94.143:8001 }  shred_version=64475 
time=2025-03-18T15:07:59.819Z level=info scope=cmd message="Starting from slot: 322941070" …
```

fix(rpc-client): http fetcher's allocator is corrupted when restarted

---

scripts/send-file.zig

`send-file.zig` is a small zig program that sends a file to a remote server over ssh using system commands (scp or rsync if available). In build.zig, it's used as a run step to send build artifacts when the build targets a remote machine, as in `zig build -Dssh-host=myserver`
The sig binary is about 200 MB, which can be time consuming to send if you don't have a fast upload speed. For example at my current location, the upload speed is 28 Mb/s, so it takes 1 minute to upload the file. At that point, it may be faster to just build the binary on the remote server.
This change adds the `--compress` flag to the rsync command when sending the file to the remote server. This compresses the data before sending it, reducing the amount of data to send by a factor of 3. Instead of 1 minute, I can …

perf(scripts): faster rsync send using compression

---

src/consensus/fork_choice.zig
src/utils/collections.zig

Using `@constCast` is a very large smell, and is unnecessary here.

fix(consensus): remove unecassary `@constCast` usage

---

readme.md
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/vm/interpreter.zig
src/vm/tests.zig

feat(fuzz): fuzz with random multithreaded reads for accountsdb

---

.github/workflows/abi_watch.yml

we would previously use a script which watches agave's gossip's Protocol `frozen_abi` (basically a recursive hash of the protocol enum's values) -- however recently that frozen_abi has been removed (see link in code change) so this script should not be run periodically anymore -- this PR comments out this, now broken, github action

ci: disable broken frozen_abi watch

---

src/runtime/borrowed_account.zig
src/runtime/feature_set.zig
src/runtime/instruction_context.zig
src/runtime/program/address_lookup_table/execute.zig
src/runtime/program/bpf_loader/execute.zig
src/runtime/program/system/execute.zig
src/runtime/program/vote/execute.zig
src/runtime/program/vote/instruction.zig
src/runtime/program/vote/state.zig
src/runtime/sysvar_cache.zig

This PR implements the following instructions:
- update_validator_identity
- Implements the instruction to update a node's identity, ie change the node_pubkey
- update_commission
- The instruction to update the commission, which is the percentage that represents what part of a rewards payout should be given to a VoteAccount, while the rest would be distributed to the delegates.
- withdraw
- Instruction used to withdraw funds from the vote account.

feat(vote-program): Update Validator Identity, Update Commission and Withdraw Instruction

---

src/rpc/server/basic.zig
src/rpc/server/linux_io_uring.zig
src/rpc/server/requests.zig
src/rpc/server/server.zig
src/trace/entry.zig
src/trace/lib.zig

Improve error handling, logs & http responses
* And some other error handling & response improvements.
* Use informative 503 Service Unavailable response for genesis file.
* Some logger refactors.
* Only use getSockName in io_uring in error log paths.
* Add missing logs to some places
Skeleton for rpc requests in basic backend
plus some miscellaneous fixes and renames

Improve error handling, logs & http responses

---

src/accountsdb/buffer_pool.zig

The Zig std hashmap was keeping us from loading mainnet snapshots due to an exponential slowdown. The array hashmap doesn't have this problem. I considered using our swissmap but its API differs enough to not go for it right now. 
The bad behaviour is described here:
https://re.factorcode.org/2023/11/factor-is-faster-than-zig.html
Related to https://github.com/Syndica/sig/issues/66. This PR represents a >200x (!!) speedup.

fix(accountsdb) buffer pool: use array hashmap 

---

src/accountsdb/accounts_file.zig
src/accountsdb/buffer_pool.zig
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/index.zig

Before, the index would use ram for:
1. All operations in loading threads
2. Pubkey ref map
Now the disk is used for both, resulting in huge memory savings for loading mainnet snapshots. As of now, you need only 13GB of ram from the gpa, whereas before it required well over 100 (couldn't measure it - system locked up long before finishing).
This PR also greatly reduces memory allocations done by code reading accounts from the buffer pool, which was necessary for some memory tracking tools.

fix(accountsdb loading): improve memory usage for mainnet

---

build.zig
build.zig.zon
src/accountsdb/accounts_file.zig
src/accountsdb/buffer_pool.zig
src/accountsdb/db.zig
src/accountsdb/download.zig
src/accountsdb/index.zig
src/accountsdb/snapshots.zig
src/cmd.zig
src/gossip/dump_service.zig
src/gossip/service.zig
src/trace/log.zig
src/utils/lib.zig
src/utils/tar.zig

Adds tracy instrumentation. Tracks various spans in our code, and tracks our allocations. Shouldn't do anything without `-Denable-tracy`.
Best explained with some screenshots:
gpa memory usage going up with accountsdb init:
a time distribution
a suspected memory leak

perf(profiling): integrate tracy

---

src/gossip/pull_response.zig
src/gossip/service.zig
src/utils/allocators.zig

These tests keep failing in the CI, making it very difficult to work. We should just disable them for now and have a tracking issue to fix them.
Tracking issue: https://github.com/Syndica/sig/issues/681

fix(testing): disable some flaky tests

---

src/accountsdb/db.zig
src/core/epoch_schedule.zig
src/runtime/program/vote/execute.zig
src/runtime/rent_collector.zig
src/runtime/sysvar/epoch_schedule.zig
src/runtime/sysvar/lib.zig
src/runtime/sysvar_cache.zig
src/runtime/testing.zig

Also fixes the sig-fuzz action, since #652 removed the `DEFAULT` field.

fix(epoch): make epoch schedule default a constant

---

scripts/style.py
src/accountsdb/db.zig
src/accountsdb/fuzz_snapshot.zig
src/accountsdb/snapshots.zig
src/rand/rand.zig

Removes `fillHashmapWithRng`, it was kind of complicated and clunky compared to just writing the same logic directly. Also adds a minimum to all the data entry lengths for certain debugging purposes I found I needed recently.
Makes snapshots.zig conform to the column length limit.

refactor(snapshots): "random init" refactor + style fix

---

src/vm/memory.zig
src/vm/syscalls/cpi.zig

Assert that the types being translated from VM memory have a stable memory layout.

fix(runtime): repr check before vm translate

---

src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/lib.zig
src/accountsdb/manager.zig

accountsdb.zig and the AccountsDB struct are overwhelmingly large. I'm writing code in replay that needs to read data from the db and it's hard to figure out where to even begin looking at this giant file to find the public facing api for loading accounts out of the database.
`AccountsDB.runManagerLoop` and the functions it calls are not ordinary functions for interacting with the database. It's really a behind-the-scenes service that runs constantly and keeps AccountsDB internally tidy, whereas AccountsDB is a data structure that other components need to read from and write to. That service and its test alone account for 1500 lines of code, contributing a lot to `accoutsdb.zig`.
I decided to split out the manager service into its own separate file. I think it's sensible to keep the data …

refactor(accountsdb): move manager loop to own file

---

src/cmd.zig

The file logging parameters were not being propagated as they should. Also the max_shreds was inconsistent with max_shreds from config.Cmd

fix(cmd): cli config for logging to a file and max shreds

---

src/vm/lib.zig
src/vm/memory.zig
src/vm/syscalls/cpi.zig

[atc_AAAAAAATADXnHYVjAzIWEg.zip](https://github.com/user-attachments/files/19985350/atc_AAAAAAATADXnHYVjAzIWEg.zip) contains the fixtures that panic if the alignment is incorrect.
Interestingly, Agave also panics under these fixtures. Panicking because of user input is incorrect, so we should prefer this solution for now, unless a better one is found.

fix(svm): alignment fixes

---

ci/run-and-update-service/sig-update
ci/run-and-update-service/sig.conf
metrics/docker-compose.yml

The grafana password is now configurable in a .env file, and this is used in the run-and-update-service. GF_SECURITY_ALLOW_EMBEDDING is now enabled so public dashboards can be embedded in iframes.

feat(grafana): customizable password and enable embedding

---

src/vm/syscalls/ecc.zig
src/vm/syscalls/hash.zig

The first commit is unfortunately pretty nasty. It seems that Agave/FD doesn't check the security of the precomputed element when doing a scalar multiplication over Edwards25519. The Zig stdlib provides this check by default without providing a way to remove it (for very good reason), but in the end, we need to match Agave, so I've pulled out the necessary functions and commented out the checks.

fix(svm): conform on some more crypto syscalls

---

src/gossip/data.zig
src/gossip/fuzz_service.zig
src/gossip/ping_pong.zig
src/gossip/prune.zig
src/gossip/service.zig
src/gossip/table.zig
src/ledger/shred.zig
src/net/lib.zig
src/net/packet.zig
src/net/quic_client.zig
src/net/socket_utils.zig
src/shred_network/repair_service.zig
src/shred_network/shred_receiver.zig
src/shred_network/shred_retransmitter.zig
src/sync/channel.zig
src/transaction_sender/transaction_info.zig

Renames the `data` field to `buffer`, adds two methods for accessing the actually-used subset of the buffer as described by `size`, `slice` & `sliceMut`. This replaces the usages which manually read `packet.data[0..packet.size]`. Usages which write directly to the buffer just become `&packet.buffer` instead.
Also re-houses the size constant, so that accessing it is `Packet.DATA_SIZE`, instead of `packet.PACKET_DATA_SIZE`, similar to `Hash.SIZE`, `Pubkey.SIZE`, etc.
Edit: also needed to update some of the code that was incidentally changed to add more test coverage to satisfy codecov.

refactor(net): Packet data buffer access & DATA_SIZE constant namespacing

---

src/core/transaction.zig
src/gossip/data.zig
src/gossip/fuzz_service.zig
src/gossip/ping_pong.zig
src/gossip/prune.zig
src/gossip/service.zig
src/gossip/table.zig
src/ledger/shred.zig
src/net/lib.zig
src/net/packet.zig
src/net/quic_client.zig
src/net/socket_utils.zig
src/shred_network/repair_service.zig
src/shred_network/shred_receiver.zig
src/shred_network/shred_retransmitter.zig
src/sync/channel.zig
src/transaction_sender/mock_transfer_generator.zig
src/transaction_sender/transaction_info.zig

Make the `signatures` field a const slice; will make it easier to initialize test data for it, and it doesn't appear to need to be mutable aside from a single instance which was trivially refactored.

refactor(core): Make Transaction signatures field a const slice

---

src/gossip/service.zig
src/shred_network/repair_service.zig
src/utils/tar.zig
src/utils/thread.zig

This consolidates the functionality from `ThreadPoolTask` with `HomogeneousThreadPool` since I need features from both in replay. Also, they are redundant - it's confusing how there are two ways to do almost the same thing. 
I added a couple features to `HomogeneousThreadPool` that were in use with `ThreadPoolTask`, and deleted `ThreadPoolTask`:
- Allow usage with a pre-existing `ThreadPool` instead of always creating its own. I specifically wanted this for replay. This is implemented with `initBorrowed`
- Constrain the number of concurrent tasks to something less than the number of threads in the pool. As a simplification, I implemented this a little different than `ThreadPoolTask`. I just track the limit with an integer and keep throwing tasks into the same array list instead of …

refactor(threadpool): consolidate thread pool usages

---

src/runtime/compute_budget.zig
src/runtime/sysvar/clock.zig
src/runtime/sysvar/epoch_rewards.zig
src/runtime/sysvar/fees.zig
src/runtime/sysvar/last_restart_slot.zig
src/runtime/sysvar/lib.zig
src/runtime/sysvar/slot_hashes.zig
src/runtime/sysvar/stake_history.zig
src/runtime/sysvar_cache.zig
src/runtime/testing.zig
src/vm/syscalls/lib.zig
src/vm/syscalls/sysvar.zig

Implements all the `sol_get_*_sysvar` syscalls, ensuring those with fixtures pass conformance tests.

feat(svm): implement `sol_get_*_sysvar`

---

src/bincode/varint.zig
src/runtime/borrowed_account.zig
src/runtime/program/bpf_loader/execute.zig
src/runtime/program/vote/execute.zig
src/runtime/program/vote/instruction.zig
src/runtime/program/vote/state.zig
src/runtime/testing.zig
src/runtime/transaction_context.zig
src/utils/collections.zig
src/vm/main.zig

fix(runtime): vote program conformance

---

src/cmd.zig
src/replay/lib.zig
src/replay/service.zig
src/replay/trackers.zig
src/sig.zig
src/trace/log.zig

This just sets up some high-level scaffolding for replay without any actual logic implemented. This is a minimal PR so dadepo and I can have a shared space to start working in asap. Most of the logic I've implemented for replay is in separate branches which can be reviewed and merged later.
Changes:
- Add `replay` folder with:
- `service.zig`: The high level state and loop for executing replay.
- `trackers.zig`: SlotTracker and EpochTracker which are used for now to keep the state in agave's bankforks. I'd like to avoid passing these structs around to too many places, but we need to keep this state in replay at a high level
- run replay in the `validator` command in cmd.zig
- Add `Logger.from` for more ergonomic switching of scopes (this will come in handy in 0.14 with decl literals)

feat(replay): scaffolding for replay stage

---

src/consensus/fork_choice.zig
src/consensus/replay_tower.zig

This adds the implementation for heaviestSlotOnSameVotedFork.
This could not be implemented until now because it depends on Tower.

refactor(consensus, forkchoice) Add `forkchoice.heaviestSlotOnSameVotedFork` method

---

src/runtime/program/bpf/execute.zig
src/runtime/program/bpf/serialize.zig

When returning the memory passed into `Region.init`s during `serializeParameters`, it uses `toOwnedSlice()` which may realloc to fit the backing (capacity-sized) allocation into `.items.len`, making the `.item` slices previously passed into `Region.init` invalid.
This returns the `ArrayList`'s full-allocated memory to be free'd, avoiding the potential realloc.
Paired with https://github.com/Syndica/sig-fuzz/pull/12

fix(runtime): avoid potential Region uaf

---

src/runtime/executor.zig
src/vm/syscalls/cpi.zig
src/vm/syscalls/lib.zig

Fix cpi syscalls to pass conformance tests. Paired with https://github.com/Syndica/sig-fuzz/pull/8

fix(svm): cpi conformance

---

src/bincode/bincode.zig
src/bincode/bounded_array.zig

Defines a standard codec for bounded arrays, so they're serialized and deserialized correctly by default.

feat(bincode): define standard codec for bounded arrays

---

src/consensus/lib.zig
src/consensus/replay_tower.zig
src/consensus/vote_parser.zig
src/consensus/vote_tracker.zig
src/consensus/vote_transaction.zig
src/core/instruction.zig
src/core/pubkey.zig
src/core/stake.zig
src/core/transaction.zig
src/gossip/table.zig
src/runtime/program/precompiles/lib.zig
src/runtime/program/vote/execute.zig
src/runtime/program/vote/instruction.zig
src/runtime/program/vote/state.zig
src/transaction_sender/mock_transfer_generator.zig

adds a method `copyAllSlotsTo` to copy all slots

refactor(consensus): Some small refactors to VoteTransaction, add method `copyAllSlotsTo`

---

build.zig.zon

Incremental compilation doesn't work for sig because one of our dependencies (libxev) uses the `usingnamespace` keyword.
I forked libxev and removed usingnamespace here: https://github.com/dnut/libxev and switched to that as sig's dependency.
Run `zig build -fincremental`. It panics on main with this error:
> error: thread 3490520122 panic: 'usingnamespace' is not supported by incremental compilation
It runs without error on this branch.

fix: incremental compilation

---

build.zig

This way `-Dno-bin -Dno-run` works even when using the install step,
whether explicitly or by default - ie, `zig build -Dno-bin -Dno-run`
no longer ignores the existence of compile errors.
I missed this in #760.

refactor(build): make install step depend on executable compilation

---

src/runtime/executor.zig
src/runtime/program/bpf/serialize.zig
src/runtime/program/testing.zig
src/runtime/stable_log.zig
src/runtime/testing.zig
src/runtime/transaction_context.zig
src/runtime/transaction_execution.zig
src/vm/syscalls/cpi.zig
src/vm/syscalls/ecc.zig
src/vm/syscalls/lib.zig
src/vm/syscalls/sysvar.zig
src/vm/tests.zig

- Most changes in this PR relate to managing pointer lifetimes in testing contexts
- When creating the trancation context, we now create and return an account cache which stores the AccountSharedData's
- The accounts within this cache must live as long as the transaction context accounts

refactor(runtime): change transaction context account to take mutable pointer to AccountSharedData

---

build.zig

This fixes two bugs in build.zig's ssh code for interacting with remote hosts and improves the readability of the code and the help message.
```
$ zig build -Dssh-host=myserver -Doptimize=ReleaseSafe sig
thread 409278 panic: error.SyntaxError
std/json/scanner.zig:746:33: 0x1608eeb in next (build)
else => return error.SyntaxError,
^
...
```
`ssh.getHostTarget` in `build.zig` was written for zig 0.13 which outputs `zig targets` in json. Since upgrading to 0.14.1, `zig targets` now outputs in zon, which fails to be parsed by `std.json`.
I updated the parsing logic in build.zig to parse the output as zon.
```
$ zig build -Dssh-host=myserver -Doptimize=ReleaseSafe sig -- validator -c testnet
/usr/bin/rsync
sig
204,409,176 100%   22.94MB/s    0:00:08 (xfr#1, to-chk=0/1)
bash: line 1: …
```

fix(build.zig): ssh.getHostTarget json->zon

---

src/runtime/program/vote/state.zig
src/utils/collections.zig

This will make the sorted map/set more easily composable in the interim between now and when we add a proper self-sorting data structure.

feat(utils:collections): add unmanaged sorted map/set, set up managed variants for deprecation

---

src/utils/collections.zig

If you serialize a SortedMap and then deserialize it, it becomes unsorted. See the test case I added. This test fails on main. This breaks the ledger database which is a problem for replaying blocks. 
SortedMap is sorted lazily. Write operations do not result in a sorted map. The map is only sorted before read operations. It uses the `max` and `is_sorted` fields to determine whether or not the map needs to be sorted before the next read.
A bincode config was added in #784 to exclude the `max` and `is_rooted` fields. This fields are being set incorrectly after deserialization. Likewise, unsorted data is assumed to be sorted.
I removed the bincode config.

fix(collections): sorted map - preserve sorting in bincode

---

build.zig

This is useful for tracking down errors in release builds.
If you build with ReleaseSafe you can't get any stack trace for errors, unless you manually enable error_tracing in build.zig.
When deploying an actual release to production, you may not want to use this flag, since it has a performance cost, but often I need to compile a release build for testing because debug builds have insufficient performance. In those cases I can really benefit from seeing error traces, so I can figure out where the error came from.

feat(build): cli configurable error tracing

---

src/cmd.zig
src/consensus/progress_map.zig
src/consensus/replay_tower.zig
src/consensus/tower.zig
src/consensus/unimplemented.zig
src/consensus/vote_listener.zig
src/replay/consensus.zig
src/replay/lib.zig
src/replay/service.zig
src/replay/trackers.zig
src/time/time.zig

Implements the consensus aspects in replay.
Features to be added in follow up PRs.
- In `handle_votable_bank` all logic that involves the following data structures. Once these data structures (or their analogous) lands on main, the implementation can be updated.
- LeaderScheduleCache
- AggregateCommitmentService
- SnapshotController
- RpcSubscriptions
- BlockCommitmentCache
- BankNotificationSenderConfig
- DuplicateSlotsTracker
- DuplicateConfirmedSlots
- UnfrozenGossipVerifiedVoteHashes
- EpochSlotsFrozenSlots
- Logic involved generating vote transactions
- Updates to blockstore's `slots_stats` (`blockstore.slots_stats.mark_rooted(new_root)`) will be done when analogous feature is added to sig's blockstore
- Pushing vote to the network
- Processing fork rest.

feat(replay): consensus integration v1

---

src/replay/consensus.zig
src/replay/edge_cases.zig
src/replay/service.zig

Also modify code to use a central replay-scoped logger, and change from "handleEdgeCases" to "processEdgeCases", since the entrypoint is essentially entirely comprised of calls to functions which are also prefixed with "process", facilitating some prefix stripping for the return value's fields.

feat(replay): main entrypoint into consensus edge cases

---

.circleci/config.yml
build.zig
build.zig.zon
codecov.yml
src/replay/confirm_slot.zig
src/replay/scheduler.zig

As you can see here, https://docs.codecov.com/docs/github-checks, CodeCov has deprecated its annotations feature. This PR removes the `codecov.yml` file that was disabling it and bumps the orb version to one that outputs a config file that doesn't contain the `annotations` field, so that CodeCov interprets it as valid.

fix PIE compilation with TSan and remove `codecov.yml`

---

src/ledger/database/hashmap.zig
src/ledger/database/rocksdb.zig
src/prometheus/registry.zig
src/rpc/server/lib.zig
src/rpc/server/server.zig
src/tests.zig

#771 broke test filters. Try `-Dfilter=<anything>` on main and chances are it won't work.
We now have "tests" that exist solely to reference other tests. These references are necessary in order for our unit tests to compile and run. Previously these references were provided by comptime blocks that would always compile no matter what.
Now they are "tests" that act as a parent for other tests. Tests compile conditionally. If one of these parent tests is not compiled, then its child tests will also not be compiled. If you use a filter that does not match the parent's name, it will not compile the parent. This will transitively exclude any of the child tests (unless they are referenced by some other mechanism that *does* match the filter).
So let's say you want to run all the ledger tests so …

fix(test): -Dfilter= option doesn't work

---

src/accountsdb/accounts_file.zig

Before, code using an FBA for the bufferpool's temp allocations would be slightly undersized, and would cause an OOM reading accounts accounts very close (a few bytes) to the 10MiB max.
This is because this function (readAccount) calls getSlice twice with the same allocator - the first read would use memory inside the FBA, leading us to have slightly too little for the second read.
This fix just deallocates the data used for the first read earlier such that the 2nd read has the memory it may need.

fix(accountsdb): fix rare OOM when loading snapshots

---

conformance/src/txn_execute.zig
src/runtime/account_loader.zig
src/runtime/transaction_execution.zig

Now conforms for the following fixtures:
`00c2dcfbd00415d3c531a19ef26901f64261e339_265678.fix`
`010e42e1d45c642f8739cf5aead3d7574d9047ed_265678.fix`
`012c43064dff9a35dc033f7a83bc755574b0a255_265678.fix`

feat(conformance): Implement fees_only path in serializeOutput

---

src/accountsdb/db.zig
src/accountsdb/index.zig

This code was copied over from sebastian's branch. It was originally how we planned to add multiple index entries for the same account in the same slot. We decided not to take this approach and merged a different fix for updating an account in the same slot (not with multiple index entries).
See this commit where I already removed this code 3fbe615b74b26a7e6b787f156f5dcbb961f16420

fix(accountsdb): remove incorrect index code from stale commit in a feature branch

---

conformance/scripts/passing_txn_fixtures.txt
src/core/transaction.zig
src/runtime/executor.zig
src/runtime/program/lib.zig
src/runtime/program/precompiles/ed25519.zig
src/runtime/program/precompiles/lib.zig
src/runtime/program/precompiles/secp256k1.zig
src/runtime/testing.zig
src/runtime/transaction_context.zig
src/runtime/transaction_execution.zig

Passed: 3373, Failed: 542 (86%)
Adds entrypoint for precompile invocation within the svm. Requires instruction datas for whole transaction to be accessible from the transaction context. This PR takes a simple approach of adding a nullable instruction_datas slice to the transaction context which populated if a precompile is present and the move_precompiles_to_svm feature is active.

feat(svm): add svm precompile entrypoints

---

src/utils/tar.zig

Cannibalised from https://github.com/Syndica/sig/pull/837
Had this code fail badly a few times, this should allow for a cleaner deinit.

fix(tar) parallel untar: attempt to join before deinit

---

src/accountsdb/db.zig

Cannibalised from #837
Now we only free old slot reference buffers *after* the reference to them has been replaced. 
This greatly reduces the likelihood of  thread safety problems when running replay

fix(accountsdb) putAccount: improve thread safety

---

build.zig.zon
src/accountsdb/buffer_pool.zig
src/accountsdb/db.zig
src/accountsdb/download.zig
src/accountsdb/index.zig
src/accountsdb/manager.zig
src/accountsdb/snapshots.zig
src/cmd.zig
src/core/bank.zig
src/gossip/dump_service.zig
src/gossip/service.zig
src/replay/commit.zig
src/replay/confirm_slot.zig
src/replay/execution.zig
src/replay/freeze.zig
src/replay/scheduler.zig
src/replay/service.zig
src/replay/svm_gateway.zig
src/replay/trackers.zig
src/runtime/account_loader.zig
src/runtime/check_transactions.zig
src/runtime/sysvar/rent.zig
src/runtime/transaction_execution.zig
src/shred_network/repair_message.zig
src/shred_network/repair_service.zig
src/sync/channel.zig
src/utils/service.zig
src/utils/tar.zig
src/utils/thread.zig

It's been very useful for debugging replay. Closes https://github.com/Syndica/sig/issues/791.
- Instruments important parts of replay with tracy zones
- Upgrades tracy dependency from 0.11.1 to 0.12.2
- Adds a few extra useful ones (in e.g. accountsdb, threadpool)
A few replay slots:
Zoom in on some batches:
Replay dispatching a thread pool task:
A memory leak:
commands used in screenshots:
`zig build sig -Dno-run -Denable-tracy=true -Doptimize=ReleaseSafe`
`sudo bash -c "ulimit -n 262140 && ./zig-out/bin/sig validator -c testnet --use-disk-index -a 512 --skip-snapshot-validation --n-threads-snapshot-unpack 6 --n-threads-snapshot-load 6"`

feat(sig): tracy instrumentation (+ update to 0.12.2)

---

src/ledger/reader.zig
src/replay/execution.zig

Replay was failing to deserialize entries from shreds when resuming a partially replayed slot because the shred starting point was off by one. This fixes the ledger reader to return the correct number of shreds processed.
After fixing that, replay fails to verify the PoH chain on resumed slots because it didn't update the progress map to have the correct hash to resume from. This fixes replay to set the correct hash in confirmation progress.

fix(replay): partial slot resume errors

---

conformance/scripts/passing_txn_fixtures.txt
conformance/src/txn_execute.zig
conformance/src/verify_transaction.zig
src/replay/confirm_slot.zig
src/replay/execution.zig
src/replay/resolve_lookup.zig
src/replay/scheduler.zig
src/replay/update_sysvar.zig
src/runtime/check_transactions.zig

supersedes #889 since that pr would introduce a bug in replay where incorrect (empty) slot hashes are going to be passed down. this pr takes those changes, and adds on top of it to get the correct slot hashes in replay.
this also refactors the lookup table resolver to combine its dependencies in a struct so it can be easily collected and passed around with clarity about what it's needed for.

 fix(runtime): fix remaining sanitization bugs v2

---

.circleci/config.yml
build.zig
src/accountsdb/db.zig
src/accountsdb/manager.zig
src/crypto/bn254/tests.zig
src/gossip/service.zig
src/ledger/reed_solomon.zig
src/net/socket_utils.zig
src/rand/weighted_shuffle.zig
src/runtime/program/zk_elgamal/tests.zig
src/shred_network/shred_deduper.zig
src/sync/channel.zig
src/utils/deduper.zig

before:
```bash
> zig build test -Dno-run && time zig build test
real    1m33.854s
user    1m12.406s
sys     0m20.096s
```
after:
```bash
> zig build test -Dno-run && time zig build test
real    0m32.424s
user    0m22.690s
sys     0m6.637s
```
This PR is just a first pass to pick some low hanging fruit. 30 seconds is still way too slow. In the future I'd like to get this down below 10 seconds.
I took a couple strategies here. In general I targeted tests that take more than 1 second.
In some cases I was able to speed up an existing test by making it more efficient, or consolidating tests that share the same slow initialization. But most of the speedups come from the usage of a new build flag I added called `long-tests`. 
I tried to identify any slow tests that seem redundant because most …

test(sig): speed up unit tests

---

scripts/kcov_test.sh

kcov should use `-Dlong-tests` just like the rest of CI

fix(kcov): not running all tests

---

build.zig

`long-tests` is a build option that determines whether to run a more exhaustive battery of very slow tests. If you enable it, the tests will take about 3 times as long, adding at least a minute of execution time for `zig build test`.
Currently the default value is `false`. The assumption is if you're running *every* test, you probably don't need such time-consuming coverage of every corner of the codebase that you haven't touched.
But if you're using filters to hone in on an area of the code, then you probably *do* want more exhaustive coverage of that area of the code. So this PR changes it so the default is false unless you are using a filter, then the default is true.
The option still remains optional and you can set it explicitly to true or false on the CLI. This PR only changes the …

build: default enable long tests when using filters

---

src/cmd.zig

There's some cases where this allocator can also blow up in memory usage, let's track it like the main gpa.

feat(cmd): trace gossip gpa's allocations

---

src/replay/consensus.zig

The initial implementation was getting the vote accounts needed to calculate the compute bank state from the epoch_stakes. Going through the Agave implementation again, made the realization this should be retrieved from the stake cache.

fix(consenus) Get vote accounts from stakes cache for computed bank state

---

docs/docusaurus/docs/code/accountsdb.md
docs/docusaurus/docs/usage/run.mdx
src/accountsdb/README.md
src/accountsdb/db.zig
src/accountsdb/fuzz.zig
src/accountsdb/index.zig
src/accountsdb/manager.zig
src/accountsdb/swiss_map.zig
src/cmd.zig
src/config.zig
src/utils/allocators.zig

And also delete global_index. As well, remove any referneces to fast loading and saving, and to any concept of a global index.
We should instead approach this problem starting from the beginning after reworking AccountIndex in the future.

refactor(accountsdb:index,allocators,cmd): Delete account index fast load/save, and global_index

---

src/net/socket_utils.zig

On macOS 26 this test just hangs; the `send`s are happening with data, but the `recv`s never get anything.
why? No idea! This could be either a macOS kernel bug or a user bug, although I don't see it being the latter yet, since the code is simple and all seems correct enough.

test: disable test that hangs on MacOS 26
